### ISSUE TITLE
&flag error

### ISSUE THREAD

**Issue by siky112** [esmBot/esmBot#107]
[error.txt](https://github.com/esmBot/esmBot/files/6424475/error.txt)
i tried to use the crossing flag emoji on an image and it did that

**Comment by TheEssem** [comment]
The crossing flag emoji isn't in the list of flags, so it won't work. It is a bit weird that it's throwing an error instead of saying it's not valid, however...

**Comment by TheEssem** [comment]
Fixed with 11ab4ad
