### ISSUE TITLE
Bot fails to execute interface function (due to execution in a DM?)

### ISSUE THREAD

**Issue by TheEgghead27** [esmBot/esmBot#111]
**Command that caused the error**
`motivate this man looked at a tumblr`

**Image that caused the error**
If the error is regarding an image command, please post a direct link to the image here.
(unlikely to be related but can be found at https://cdn.discordapp.com/attachments/802320451610214430/839640182928048138/unknown.png) 

**To Reproduce**
1. Direct Message esmBot a command.
2. esmBot tries to set the typing trigger
3. See error

**Self-hosted instance?**
Did the error occur on a self-hosted instance (e.g. not the main esmBot or esmBot Dev instances)?
No
**Error file**
```
Message: TypeError: this.message.channel.sendTyping is not a function

Stack Trace: TypeError: this.message.channel.sendTyping is not a function
    at MotivateCommand.run (/home/esmBot/esmBot/classes/imageCommand.js:92:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/home/esmBot/esmBot/events/messageCreate.js:89:20)
```

**Additional context**
My theory is that there is an issue with setting the typing trigger in direct messages, likely to do with the bot's library.

**Comment by TheEssem** [comment]
This alongside #112 are both fixed with 56113a1. Will be part of the 1.5.2 release.
