### ISSUE TITLE
Self-hosted bot can't manipulate online gifs

### ISSUE THREAD

**Issue by frykher** [esmBot/esmBot#113]
**Command that caused the error**
caption, wide, soos, any command that deals with an image

**Image that caused the error**
Any image from both tenor and giphy (i saw an issue specific to giphy but mine also has a problem with tenor)

**To Reproduce**
1. Use /tenor command on discord
2. Click on any gif
3. Use an image command after posting the gif

**Self-hosted instance?**
It occurred on a self-hosted instance of the bot on a docker container. I ran several clean builds of docker-compose and wiped both images and containers multiple times.

**Error file**
```
Message: Error: Magick: no decode delegate for this image format `DAT' @ error/constitute.c/ReadImage/572

Stack Trace: Error: Magick: no decode delegate for this image format `DAT' @ error/constitute.c/ReadImage/572
    at /home/esmBot/.internal/utils/image-runner.js:19:40
    at new Promise (<anonymous>)
    at Object.exports.run (/home/esmBot/.internal/utils/image-runner.js:5:10)
    at Object.<anonymous> (/home/esmBot/.internal/utils/image-runner.js:32:8)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:182:24)
```

**Additional context**
The bot works completely fine on downloaded gifs, just not ones from the internet.

**Comment by TheEssem** [comment]
The gifs from Tenor may or may not require an API key; it is a bit weird that the version of ImageMagick in the containers won't decode the gifs as videos, however. The Giphy ones are definitely the hardest due to them loading as a website, but the latest commits should help alleviate the issue. Are you on the latest commit?

**Comment by frykher** [comment]
I'll pull right now, clean docker builds take like 15 mins on my machine though so hold tight

**Comment by frykher** [comment]
Alright, I found out something really interesting. Whereas my self-hosted bot would crash on gifs, esmBot just hangs on processing. Here's what I mean:
![image](https://user-images.githubusercontent.com/62032183/117376060-60fa1500-ae9e-11eb-8a00-6f0f7b665fb5.png)
(This is on the latest commit of pain)

**Comment by frykher** [comment]
I take back what I said, it's inconsistent.
![image](https://user-images.githubusercontent.com/62032183/117378253-044d2900-aea3-11eb-818a-0c24dcca7751.png)
Tenor gif for both of them
This time, it's actually running directly off node, not docker

**Comment by frykher** [comment]
![image](https://user-images.githubusercontent.com/62032183/117378352-3bbbd580-aea3-11eb-9805-9b3735652e92.png)

**Comment by TheEssem** [comment]
The main bot taking ages to run is a result of #55/#56. Gonna try and add proper support for MP4 files in the containers so that it can decode Tenor gifs without needing to use the API.

The latest screenshot seems to be a database connection issue; are you sure all of the containers are running?

**Comment by frykher** [comment]
Oh, yeah that issue was completely irrelevant. Still getting "no decode delegate" 😔

**Comment by frykher** [comment]
yeah uh, it turns out i'm an idiot and didn't enable the image api and didn't include the tenor api key in the env file. additionally, when i did realize that and change the values, it kept using the old ones (very weird). then I deleted and cloned the repository and everything worked fine.

I'm super sorry for wasting your time, but for anyone looking at this issue in the future, make sure you set API to true and the TENOR variable to your api key 🙏

**Comment by frykher** [comment]
on another note as a quick thing, how would you go about setting up a web server for gifs? this is a self-hosted bot that only my friends will primarily use so I don't need it to be temporary

**Comment by TheEssem** [comment]
> on another note as a quick thing, how would you go about setting up a web server for gifs? this is a self-hosted bot that only my friends will primarily use so I don't need it to be temporary

You can use something like [nginx](https://nginx.org/) to serve files over the web, there are plenty of guides around on how to install/configure it. You might need a custom domain if you don't want others to see the direct server IP; if you don't want to pay for a unique domain, you can get a free subdomain over at [No-IP](https://www.noip.com/).

**Comment by frykher** [comment]
It's fine, I was planning on using Nginx but since I need it to be a permanent storage, it would be a lot of content inside the directory, to which I would need to constantly scale up the size of the SSD on the VM. Instead, I've opted to modify the code itself to upload the images to a google cloud bucket that is accessible via my custom domain.

**Comment by TheEssem** [comment]
> It's fine, I was planning on using Nginx but since I need it to be a permanent storage, it would be a lot of content inside the directory, to which I would need to constantly scale up the size of the SSD on the VM. Instead, I've opted to modify the code itself to upload the images to a google cloud bucket that is accessible via my custom domain.

Ah, very nice solution! I'd be willing to implement something like that in the main bot, you can send a PR if you want. :)

**Comment by longdas** [comment]
> 

> Instead, I've opted to modify the code itself to upload the images to a google cloud bucket that is accessible via my custom domain.

Why not just use a docker bind mount?

**Comment by frykher** [comment]
S3 storage afaik can't be used as a docker volume

**Comment by samhza** [comment]
On May 8, 2021 1:10:06 AM EDT, Fahim ***@***.***> wrote:
>S3 storage afaik can't be used as a docker volume
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/esmBot/esmBot/issues/113#issuecomment-835103161
There is a fork of esmBot that uses S3 for storing large memes, it's called esmbot-lite, it's changes are worth giving a try.

**Comment by TheEssem** [comment]
This issue is getting pretty off topic, locking it for now. If you want to continue discussion, you can create a new issue or discuss it in the esmBot Support server.
