### ISSUE TITLE
Bot doesnt reply

### ISSUE THREAD

**Issue by Daxxboii** [esmBot/esmBot#115]
**Command that caused the error**
Post the exact command that caused the error.

**Image that caused the error**
If the error is regarding an image command, please post a direct link to the image here.

**To Reproduce**

**Self-hosted instance?**
Did the error occur on a self-hosted instance (e.g. not the main esmBot or esmBot Dev instances)?

**Error file**
```
Post the contents of the error file here.
```

**Additional context**
[error.txt](https://github.com/esmBot/esmBot/files/6445557/error.txt)

**Comment by TheEssem** [comment]
As the message says, it's not really an error.
