### ISSUE TITLE
RSS memory leak with native image functions

### ISSUE THREAD

**Issue by TheEssem** [esmBot/esmBot#116]
With the switch to native, Magick++-based functions for image processing, there seems to be a bit of a memory leak whenever an image function is run. It seems to grow a bit more on the first run; however, this might just be Magick++ initializing everything on the first run. Each run seems to be increasing the shared memory size, which could (possibly) be a result of a worker not properly freeing its used memory.

This was previously thought to only occur on glibc-based distributions; however, it seems like musl has the same issue. Alternative memory allocators like jemalloc or mimalloc don't seem to help the issue either, and valgrind doesn't pick up anything meaningful. Any comments/suggestions regarding this issue are appreciated.

**Comment by TheEssem** [comment]
Figured out that passing in raw file buffers (as done with 61758fa3bb57faa92633dfc34ab5e0925ef73e7a) seems to lower memory usage a bit. I assume that it tries to cache the images in memory even after it's done with them?

**Comment by zurgeg** [comment]
Maybe [this post on the Legacy ImageMagick Fourms](https://legacy.imagemagick.org/discourse-server/viewtopic.php?t=8384) might be meaningful? It also might be worth bookmarking [this SO post](https://stackoverflow.com/questions/63440339/magick-napi-module-memory-leak) to see if it gets any answers, seems like that question is asking about this problem too.

**Comment by zurgeg** [comment]
After further research, that fourm post seems to have the answer solved with a patch made in 2008, and the SO post was made by you, oops.

**Comment by siky112** [comment]
[error (1).txt](https://github.com/esmBot/esmBot/files/7629087/error.1.txt)
This is probably a memory leak too. Gif used is [this.](https://tenor.com/view/smurfs-dance-party-smurf-dance-smurf-gif-22270951)

**Comment by TheEssem** [comment]
> [error (1).txt](https://github.com/esmBot/esmBot/files/7629087/error.1.txt) This is probably a memory leak too. Gif used is [this.](https://tenor.com/view/smurfs-dance-party-smurf-dance-smurf-gif-22270951)

This is unrelated, it's probably due to some cache cleanup stuff.

**Comment by TheEssem** [comment]
New findings: this seems to happen regardless of whether or not Magick++ is used, which leads me to believe that it's an issue with how node-addon-api and NAPI handle buffers and threading. This also seems to occur on Win32 systems somewhat, although the impact on there seems to be lessened; same thing when using the jemalloc allocator on Linux.

I believe that the issue at hand isn't that the actual native memory isn't freed; it's that it's being held onto by the process(es) for whatever reason even after it's done with it, resulting in a high RSS size. The fact that jemalloc reduces the impact of the issue significantly (though not entirely) makes me think that there's a memory fragmentation issue in there somewhere.

**Comment by bjcscat** [comment]
perhaps try freeing the char pointer result, my handler does it for the revamped native modules but the old ones do not free the char pointer used to construct the napi result buffer
im 99.99% sure node api just copies it over

**Comment by bjcscat** [comment]
Nevermind, what I said was stupid. Node does NOT copy it over but does allow you to supply a callback that will be invoked upon GC

**Comment by TheEssem** [comment]
This no longer appears to be an issue. Newer memory issues I've noticed seem to be caused by individual commands, and never due to a memory leak over time.
