### ISSUE TITLE
AbortController is not defined and newArgs.join(...).replaceAll is not a function

### ISSUE THREAD

**Issue by 0vertime-dev** [esmBot/esmBot#118]
**Command that caused the error**
the caption command caused both of theese

**Image that caused the error**
If the error is regarding an image command, please post a direct link to the image here.
1st error image https://media.discordapp.net/attachments/680928395399266314/836039028217217035/image0-9.gif
2nd error image https://tenor.com/view/epic-embed-fail-ryan-gosling-cereal-embed-failure-laugh-at-this-user-gif-20627924

**To Reproduce**
I have no idea, all I did is not have a database, and put "DB=dummy" like the wiki says

**Self-hosted instance?**
Did the error occur on a self-hosted instance (e.g. not the main esmBot or esmBot Dev instances)?
Self hosted

**Error file**
[error (1).txt](https://github.com/esmBot/esmBot/files/6449685/error.1.txt)
[error (2).txt](https://github.com/esmBot/esmBot/files/6449683/error.2.txt)

**Additional context**

**Comment by samhza** [comment]
The minimum required Node.js version should be added to the install docs
on the wiki.

**Comment by samhza** [comment]
The issue can probably be closed now.

**Comment by 0vertime-dev** [comment]
I tried reinstalling nodejs and it didn't help, I tried setting up the PostgresSQL database but when I put in "DB=postgresql://esmbot:verycoolpass100@postgres:5432/esmbot" into the .env I get the error
"Error: getaddrinfo EAI_AGAIN Postgres"

**Comment by TheEssem** [comment]
> sorry for not getting back
> 
> I tried reinstalling nodejs and it didn't help, I tried setting up the PostgresSQL database but when I put in "DB=postgresql://esmbot:verycoolpass100@postgres:5432/esmbot" into the .env I get the error
> "Error: getaddrinfo EAI_AGAIN Postgres"

It seems that you capitalized the beginning of `postgres` in your config. It needs to be case-sensitive.

Also, might I ask what distribution you're using?

**Comment by TheEssem** [comment]
The original issue was solved and the reporter has not responded to a question regarding the second issue, closing.
