### ISSUE TITLE
Error occurring while using the caption command

### ISSUE THREAD

**Issue by ok-notok** [esmBot/esmBot#119]
**Command that caused the error**
Post the exact command that caused the error.

&caption insert caption here

**Image that caused the error**
If the error is regarding an image command, please post a direct link to the image here.

All images I have tried have been from Tenor GIFS inside of discord itself. Here is one:
https://tenor.com/view/lil-yachty-drake-oprahs-bank-account-meme-laptop-gif-20803826

**To Reproduce**
1. Send a discord GIF through Tenor in a discord chat
2. Use the &caption command
3. Get an error

**Self-hosted instance?**
Did the error occur on a self-hosted instance (e.g. not the main esmBot or esmBot Dev instances)?

No, the command was executed on the main esmBot.

**Error file**
```
Message: FetchError: request to http://127.0.0.1:8081/status failed, reason: socket hang up

Stack Trace: FetchError: request to http://127.0.0.1:8081/status failed, reason: socket hang up
    at ClientRequest.<anonymous> (/home/esmBot/esmBot/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (node:events:365:28)
    at Socket.socketOnEnd (node:_http_client:471:9)
    at Socket.emit (node:events:377:35)
    at endReadableNT (node:internal/streams/readable:1312:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by TheEssem** [comment]
Seems to be a connection issue with the API servers. Should be resolved for now.
