### ISSUE TITLE
&sphere error

### ISSUE THREAD

**Issue by grantlmul** [esmBot/esmBot#125]
**Command that caused the error**
&sphere

**Image that caused the error**
https://cdn.discordapp.com/attachments/841889612406456363/845000802376089600/jpeg.jpg

**To Reproduce**
&sphere

**Self-hosted instance?**
no

**Error file**
[error.txt](https://github.com/esmBot/esmBot/files/6517985/error.txt)

**Additional context**
N/A

**Comment by TheEssem** [comment]
Seems like something happened to the API server, should be fixed now.
