### ISSUE TITLE
"Processing... this might take a while"

### ISSUE THREAD

**Issue by te-agma-at** [esmBot/esmBot#127]
**Describe the bug**
Please fix EsmBot's image manipulation commands (Slow while doing a command)

**To Reproduce**
1. Go on Discord
2. Type any image manipulation command
3. Wait. If you wait for 1 hour or more, the bot may not work at all.

**Expected behavior**
1, Type any image manipulation command
2. Bot runs and completes task given by command in less than 1 hour or more

**Screenshots**
![Screenshot 2021-05-28 195017](https://user-images.githubusercontent.com/72958435/120051286-0449d000-bfee-11eb-8410-e7c28a6bb351.png)

**Self-hosted instance?**
No

**Additional context**
It appears this happened more than once, particularly with the bot being slow at least multiple times already.

**List of emojis while taking so long**
:processing:
:glxgears:
:processing: - This "processing" emoji is now green, and instead of the usual gears, there's spinning and shapeshifting polygons
"Spunch Bop" processing emoji - I wasn't even able to retrieve the name of this emoji, but it shows the famous "Spunch Bop" moving fast in weird effects.
Let me know if you manage to find more proccessmojis in replies.

**Comment by TheEssem** [comment]
See #56
