### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Dejasith** [esmBot/esmBot#128]
**Command that caused the error**
Post the exact command that caused the error.

**Image that caused the error**
If the error is regarding an image command, please post a direct link to the image here.

**To Reproduce**

**Self-hosted instance?**
Did the error occur on a self-hosted instance (e.g. not the main esmBot or esmBot Dev instances)?

**Error file**
```
Post the contents of the error file here.
```

**Additional context**

![Screenshot (812)](https://user-images.githubusercontent.com/85003369/120056181-d2d60200-bff7-11eb-9502-838197427a3e.png)

**Comment by samhza** [comment]
Lavalink connection issue, see #39 for info.
