### ISSUE TITLE
the letter j becomes i in the caption command

### ISSUE THREAD

**Issue by walter-the-dog** [esmBot/esmBot#132]
**Describe the bug**
the letter j becomes i in the caption command

**To Reproduce**
1. take image
2. do please caption j
3. See error

**Expected behavior**
to see the letter j instead of i

**Self-hosted instance?**
No it happened on the official bot

**Comment by staticsquidd** [comment]
That's just the font that the command uses. If you put a caption with j and i next to eachother, you can see that the j extends further than the i. It's just a style thing.
