### ISSUE TITLE
Message components support for pagination

### ISSUE THREAD

**Issue by TheEssem** [esmBot/esmBot#134]
It could probably be worthwhile to replace the reactions on paginated messages with the new message components system: https://discord.com/developers/docs/interactions/message-components

~~This PR would need to be merged before implementing this, however: https://github.com/abalabahaha/eris/pull/1189~~ It's still possible to do it without this merged.

**Comment by samhza** [comment]
Some ideas for commands being merged:
stats,imagestats -> stats
qrread,qrcreate -> qr {read,create}
dev commands (eval, reload, etc) -> dev *

**Comment by TheEssem** [comment]
Implemented with da709c4. Will revisit once Eris merges in proper component/interactions support.
