### ISSUE TITLE
&channel command doesn't work instantly.

### ISSUE THREAD

**Issue by krzesu0** [esmBot/esmBot#135]
**Describe the bug**
Both `&channel enable` and `&channel disable` won't work instantly.

**To Reproduce**
1. Type `&channel disable`
2. Use commands as normal.

Using commands result in normal output.

After some time (I don't know the exact value, we tried it again about 20hrs later). It stopped responding **on that channel only**.
Exactly the same the other way.
1. Type `&channel enable`
2. Use commands as normal.

Using commands result in **no** output.

**Expected behavior**
Both `&channel disable` and `&channel enable`  should work instantly

**Screenshots**
https://imgur.com/a/FD4fM9y

**Self-hosted instance?**
Main esm-bot. Idk if it applies also to self-hosted.

**Comment by TheEssem** [comment]
hmmm, I noticed that issue the other day and made a quick fix on esmbot dev, gonna try and push it here as well as on the main bot

**Comment by TheEssem** [comment]
(hopefully) fixed
