### ISSUE TITLE
Request time out

### ISSUE THREAD

**Issue by geORgehyphen4** [esmBot/esmBot#138]
&uncaption

https://media.discordapp.net/attachments/676177708795035699/811666880300974130/6bb0dea.gif

1. post image
2. use command
3. See error

bot worked normally up to command, also worked fine after

Message: Error: Request timed out (>16000ms) on POST /channels/842087710168449067/messages

Stack Trace: Error: Request timed out (>16000ms) on POST /channels/842087710168449067/messages
    at Timeout._onTimeout (/home/esmBot/esmBot/node_modules/eris-sharder/src/structures/SyncedRequestHandler.js:20:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

**Comment by samhza** [comment]
Seems to be a transient error and not one with the code, retrying the command
again seemed to work.

**Comment by TheEssem** [comment]
Like @samhza said, this is more of an issue with Eris connecting to Discord than it is with the bot itself.
