### ISSUE TITLE
Private files are exposed publicly through bots internal API

### ISSUE THREAD

**Issue by UnacceptableUse** [esmBot/esmBot#144]
### Describe the bug

By navigating to the /running URL on the bot's internal API, which is publicly accessible, you can view all currently running image jobs, including captions and URLs. This means that by polling this endpoint, a malicious user could download all images used in image commands, which is a privacy issue.   
  
I won't link to the URL here to avoid giving anyone the opportunity, but it is relatively easy to find.

### Self-hosted instance?

No

**Comment by TheEssem** [comment]
The endpoint in question is only for a single API server, so thankfully it isn't all of the jobs. Nonetheless, it should now be fixed with a firewall rule edit.

**Comment by UnacceptableUse** [comment]
Looks like it's still accessible

**Comment by TheEssem** [comment]
> Looks like it's still accessible.
> Thanks for the quick response, by the way

That's weird, I can't seem to access it from my PC anymore. Mind sending me a DM on Discord about this so we can discuss it in private? My tag is Essem#9261.

**Comment by UnacceptableUse** [comment]
Sure.

**Comment by TheEssem** [comment]
Extra measures have been taken with commit 77ca0fd to prevent the IPs from leaking as well.
