### ISSUE TITLE
caption not working

### ISSUE THREAD

**Issue by thatrtxdude** [esmBot/esmBot#146]
### Command that caused the error

&caption

### Image that caused the error

https://tenor.com/view/scared-freak-out-clutch-my-pearls-gasp-scary-gif-5496313

### Steps to reproduce

1. type in &caption
2. done

### Self-hosted instance?

No

### Error file

Message: libMagick++-7.Q16HDRI.so.5: cannot open shared object file: No such file or directory

Stack Trace: undefined

**Comment by TheEssem** [comment]
Seems that the sandbox I had running on one of the servers didn't properly launch, should be fixed now.
