### ISSUE TITLE
RGB Color space not permitting error when attempting to use deepfry

### ISSUE THREAD

**Issue by XenoPanther** [esmBot/esmBot#149]
### Command that caused the error

&deepfry

### Image that caused the error

https://cdn.discordapp.com/attachments/757243496200667246/874032118525734972/DDB51ED7-75B6-48EA-9E02-BF0181568922_-_Copy.png

### Steps to reproduce

1. posted image with &deepfry / reply to 
2. RGB color space not permitted on grayscale PNG error occurs

### Self-hosted instance?

No

### Error file

```
Message: Magick: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `​' @​ warning/png.c/MagickPNGWarningHandler/1748

Stack Trace: undefined
```

**Comment by TheEssem** [comment]
Should be fixed with cbc2918.
