### ISSUE TITLE
Doing any command results in error; "No space left on device"

### ISSUE THREAD

**Issue by CeledonianError** [esmBot/esmBot#152]
### Command that caused the error

&caption, &motivate, &meme, possibly more

### Steps to reproduce

1. Do anything (tested with &caption, &motivate and &meme)
2. See error

### Self-hosted instance?

No

### Error file

```
Message: Magick: unable to extend cache '': No space left on device @​ error/cache.c/OpenPixelCache/3901

Stack Trace: undefined

```

**Comment by TheEssem** [comment]
Seems that the cronjob I have set to run on each server didn't exist on one of them, should be fixed now.
