### ISSUE TITLE
Prune temporary images

### ISSUE THREAD

**Issue by samhza** [esmBot/esmBot#153]
Currently the files esmBot puts in `TEMPDIR` are not pruned by the bot. It's possible for people running the bot to prune the folder through other means, on the live bot they are pruned through a cronjob. It'd be better for this to be baked into esmBot itself.

esmBot should have be a THRESHOLD env option. Whenever TEMPDIR's file sizes total more than THRESHOLD bytes, esmBot will delete files, oldest first, until the file sizes are less than THRESHOLD.

**Comment by samhza** [comment]
This behavior, if enabled by default, would prevent situations such as #152

**Comment by samhza** [comment]
Another problem with using a 30 minute timer to prune images is that it is possible for someone to make a meme and then it is deleted before Discord even has time to display it to the user

**Comment by TheEssem** [comment]
Fixed by #249
