### ISSUE TITLE
Caption Error

### ISSUE THREAD

**Issue by DerHerrSturm** [esmBot/esmBot#155]
### Command that caused the error

&caption Murphy

### Image that caused the error

https://tenor.com/view/dancing-garfield-jon-arbuckle-dance-moves-moves-gif-16386584

### Steps to reproduce

1. Go to 'Discord Text Channel'
2. Click on 'Message Box'
3. Paste the link 'https://tenor.com/view/dancing-garfield-jon-arbuckle-dance-moves-moves-gif-16386584'
4. Press Enter
5. Click on 'Message Box'
6. Type "&caption Murphy'
7.  See error

### Self-hosted instance?

No

### Error file

```
Message: Error: connect ECONNREFUSED <redacted>:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1142:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '<redacted>',
  port: 5432
}

Stack Trace: Error: connect ECONNREFUSED <redacted>:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1142:16)

```

### Additional context

This has been happening in multiple servers, with multiple commands (&fart) and with other images as well.

**Comment by TheEssem** [comment]
This was an issue with PostgreSQL crashing, most likely due to the massive amount of caching that ImageMagick was doing. Removed the image server that was causing the issue for now, should be good to go.
