### ISSUE TITLE
&uncaption error

### ISSUE THREAD

**Issue by anakinlmao** [esmBot/esmBot#157]
### Command that caused the error

&uncaption

### Image that caused the error

https://images-ext-1.discordapp.net/external/F-GT23muRJCwucacQj_x40jJu6lkVGNMGJpoDiKVjW0/https/media.discordapp.net/attachments/879478929356886028/882891619597160488/woman_is_talking.gif?width=320&height=174

### Steps to reproduce

just try to &uncaption

### Self-hosted instance?

No

### Error file

```
Uh oh! I ran into an error while running this command. Please report the content of the attached file at the following link or on the esmBot Support server: https://github.com/esmBot/esmBot/issues

Message: WebAssembly.instantiate(): Out of memory: wasm memory

Stack Trace: undefined
```

**Comment by TheEssem** [comment]
Related to #116 maybe?

**Comment by TheEssem** [comment]
Seems like this can happen when a worker has started and there isn't enough memory to make a request to get the image. Seeing as there's not much that can be done about this and it doesn't seem to be happening on the main instance, I'm closing this for now.

If you're having this issue on a self-hosted instance, check if you have enough free RAM.
