### ISSUE TITLE
&caption is broken; "Something happened to the image servers before I could receive the image."

### ISSUE THREAD

**Issue by te-agma-at** [esmBot/esmBot#158]
### Command that caused the error

&caption

### Image that caused the error

https://media.discordapp.net/attachments/819561823031918622/883533312101064744/BOGUSWILLNOT.gif

### Steps to reproduce

1. Go to a discord channel
2. Type &caption with a GIF
3. Wait for a while
4. Go back to that channel
5. See error
The error may not be reproduced if it doesn't show the error message and runs smoothly.

### Self-hosted instance?

No

### Error file

```
Message: Something happened to the image servers before I could receive the image. Try running your command again.

```

**Comment by TheEssem** [comment]
This happens when the bot loses connection to an image server, either through a restart or some other means. In most cases, you should just be able to run it again like the message says.
