### ISSUE TITLE
"Admiral | Service image died :(" when doing &caption

### ISSUE THREAD

**Issue by lemon-sh** [esmBot/esmBot#159]
### Describe the bug

Whenever I try to &caption certain large images, the bot says "Processing... This might take a while" and never responds. Instead, five messages appear in the bot console:
```
[WARN] - Admiral | Service image disconnected :( 
[WARN] - Admiral | Service image died :( 
[MAIN] - Admiral | Restarting service image 
[MAIN] - Service image | Starting service image 
[MAIN] - Service image | Service image is ready!
```

### Steps to reproduce

1. Find a large GIF (or image) like this one: https://tenor.com/view/hololive-nekomata-okayu-cute-kawaii-new-outfit-gif-17492412
2. Use &caption on it

### Expected behavior

The bot should process larger images just like the small images.

### Screenshots

![image](https://user-images.githubusercontent.com/26277478/132548730-fcd06135-f275-45c4-b72a-4edc9739a1b4.png)
![image](https://user-images.githubusercontent.com/26277478/132548680-93765164-aa61-46a7-a54b-f7c5ed15f425.png)

### Self-hosted instance?

Yes

### Additional context

* I am running Alpine Linux 3.12 x64 with 768MB of RAM and Node.js v16.8.0
* This issue persists on both Tenor links and user-uploaded image files and seems to be related to the *resolution* rather than the *filesize* but I'm not certain.

**Comment by TheEssem** [comment]
Have you tried limiting the amount of memory usage in `/etc/ImageMagick-7/policy.xml`? https://imagemagick.org/script/security-policy.php

**Comment by lemon-sh** [comment]
Thank you for responding.
Interestingly, I have confirmed it to be a memory usage issue: when I try to process these larger GIFs, the imagemagick process will eat up 600MB and then crash.

I have tried setting the "memory" value in policy.xml to 256MiB but it did not fix the issue. Can you give me some advice how I should set these policy values?

**Comment by TheEssem** [comment]
Hmmm, could be related to #116 then. Unfortunately, this means that 768MB of RAM might not be enough and you might need a slightly more powerful system. (This might change in the future with a migration to libvips/ffmpeg)

Does `magick -list policy` say anything useful?

**Comment by TheEssem** [comment]
Image processing has been refactored to be per-process, so this exact issue can no longer occur. Closing now.
