### ISSUE TITLE
Make bot stay in VC even after queue ends

### ISSUE THREAD

**Issue by samhza** [esmBot/esmBot#164]
Maybe like 15min

**Comment by TheEssem** [comment]
Still not too sure if I want to do this or not

**Comment by samhza** [comment]
Why not

**Comment by TheEssem** [comment]
I feel it would both create a sort of uneasy feeling for some privacy-conscious people and waste quite a bit of bandwidth on the server

**Comment by meow6969** [comment]
you could make the bot force itself to be server muted so that discord doesnt send any voice packets to the bot while its sitting in vc

**Comment by samhza** [comment]
> I feel it would both create a sort of uneasy feeling for some
> privacy-conscious people
I have not heard any esmBot users say this in the Discord server
or on the issue tracker. The bot could already hypothetically listen in
on voice conversations whether it's playing music or not. The bot could
already hypothetically listen in on messages in text channels it can
see. I don't see how this feature being added would give the bot more of
an ability to spy on users.
> and waste quite a bit of bandwidth on the server
The bot does not have to continuously stream silence for this feature.

**Comment by TheScreechingBagel** [comment]
Bots can be server-deafened without being muted, so that could indeed be an option. I believe some music bots used to do that as well

**Comment by TheEssem** [comment]
Seeing as a compromise has been implemented with 14046a811ae6954fbad9ed4263db9471f26e1e9e, I think it's safe to close this one. If anyone else wants this on the main bot, please let me know.
