### ISSUE TITLE
Don't assume 8MB attachment limit

### ISSUE THREAD

**Issue by ghost** [esmBot/esmBot#165]
https://github.com/esmBot/esmBot/blob/ae2ebe0337ae06ff9d3bd35b808024c250f73887/events/messageCreate.js#L116

Servers with 7 or more boosts have 50MB upload limit for all members including bots.

**Comment by meow6969** [comment]
![image](https://user-images.githubusercontent.com/75815262/137374789-0b675533-747f-4bd4-81e1-cd31fe689d12.png)
