### ISSUE TITLE
&caption causes "ran into an effor while running this command"

### ISSUE THREAD

**Issue by RealRUBB3R** [esmBot/esmBot#175]
### Command that caused the error

&caption

### Image that caused the error

https://tenor.com/view/opossum-cute-roomba-eat-eating-out-gif-16016450

### Steps to reproduce

1. Go to channel with esmBot in it
2. Type "&caption (text goes here)
3. Witness the error

### Self-hosted instance?

No

### Error file

[errorpossumgif.txt](https://github.com/esmBot/esmBot/files/7532549/errorpossumgif.txt)

**Comment by TheEssem** [comment]
Seems that one of the image processing servers went down for some reason. Managed to restart it, it should be good to go now.

**Comment by TheEssem** [comment]
Spoke too soon, the server is down again. This is quite confusing.

**Comment by kazakhDaslich** [comment]
I'm getting this issue too. Any idea when it will be fixed?

**Comment by TheEssem** [comment]
The server in question has been replaced. Should be fine now.
