### ISSUE TITLE
Caption command error

### ISSUE THREAD

**Issue by Repytwid** [esmBot/esmBot#176]
### Command that caused the error

&caption //НСЧПМ - @Inferno

### Image that caused the error

https://cdn.discordapp.com/attachments/685913191523549242/909176072715788348/ezgif.com-gif-maker_3.gif

### Steps to reproduce

step 1) post gif on discord
step 2) run &caption command
step 3) see error

### Self-hosted instance?

No

### Error file

```
Message: Magick: unable to extend cache '': No space left on device @​ error/cache.c/OpenPixelCache/3901

Stack Trace: undefined
```

**Comment by TheEssem** [comment]
The server this was happening on did not have the caching properly set up, should be fixed now.

**Comment by kreh** [comment]
I'm receiving this too - exact same process as this issue was defining.

**Comment by kreh** [comment]
**Image that caused the error**
https://media.tenor.co/videos/47a7fa44ede87b8826e0f20be550c730/mp4

**Error file**
```
Message: Magick: unable to extend cache '': No space left on device @​ error/cache.c/OpenPixelCache/3900

Stack Trace: undefined
```
