### ISSUE TITLE
error with &caption command

### ISSUE THREAD

**Issue by yaukari** [esmBot/esmBot#178]
### Command that caused the error

&caption

### Image that caused the error

https://discord.com/channels/905355396024246282/905355396024246285/909596716477612072

### Steps to reproduce

1. post gif
2. run &caption command

### Self-hosted instance?

No

### Error file

[error.txt](https://github.com/esmBot/esmBot/files/7535000/error.txt)

**Comment by TheEssem** [comment]
The bot had some trouble connecting to a specific image server, it should be restarting now.
