### ISSUE TITLE
Message: magick: CorruptImageProfile `xmp' @ warning/profile.c/SetImageProfileInternal/1882.   Stack Trace: undefined

### ISSUE THREAD

**Issue by Nicknackatory** [esmBot/esmBot#18]
Message: magick: CorruptImageProfile `xmp' @ warning/profile.c/SetImageProfileInternal/1882.

Stack Trace: undefined

**Comment by TheEssem** [comment]
Seems to be fixed for the most part on master, however I will reopen this issue if it still occurs after the 1.4 release.

**Comment by TheEssem** [comment]
Seems to still be occurring (although it seems like it might be doing it silently), reopening.

**Comment by TheEssem** [comment]
Haven't seen this issue in a long while, closing again as fixed.
