### ISSUE TITLE
A Mars candy bar image caused an error.

### ISSUE THREAD

**Issue by xSpiderHG** [esmBot/esmBot#181]
### Command that caused the error

&meme mars; &caption mars

### Image that caused the error

https://media.discordapp.net/attachments/849907047688044575/910979927782879232/Mars.png?width=1440&height=597

### Steps to reproduce

1. Send the Mars bar image.
2. Type in "&meme mars" or "&caption mars".
3. The bot should send out an error message file.

### Self-hosted instance?

No

### Error file

Message: Cannot find module '../build/Release/image.node'
Require stack:
- /root/esmBot/utils/image-runner.js

Stack Trace: undefined

**Comment by TheEssem** [comment]
Had to reinstall some packages on the server to deal with some stuff earlier, looks like you might've gotten caught up in that. Should be fixed now.
