### ISSUE TITLE
Bug while using the &caption command

### ISSUE THREAD

**Issue by Maxamalamute123** [esmBot/esmBot#183]
### Describe the bug

I tried to use the &caption command to overlay some text onto a gif.

Message: request to http://<redacted>:8080/status failed, reason: read ECONNRESET

Stack Trace: undefined

### Steps to reproduce

1. Download a gif
2. Post it in a channel
3. Use the &caption command

### Self-hosted instance?

Yes

**Comment by TheEssem** [comment]
Something must have happened to one of the server connections, should be fine now.
