### ISSUE TITLE
caption command not morking

### ISSUE THREAD

**Issue by guy0on0the0internet** [esmBot/esmBot#185]
### Command that caused the error

&caption white women when they hear on the radio the crapiest music you've ever heard in your life

### Image that caused the error

https://tenor.com/view/sesame-street-sped-up-dj-elmo-dancing-ernie-dance-gif-23245789

### Self-hosted instance?

No

### Error file

Message: Loop ended before all servers could be checked

Stack Trace: undefined

**Comment by HotelTransylvania** [comment]
I also keep getting the problem.

**Comment by TheEssem** [comment]
Duplicate of #133
