### ISSUE TITLE
esmbot captioning does not work

### ISSUE THREAD

**Issue by Chris2918** [esmBot/esmBot#186]
### Command that caused the error

@esmbot caption

### Image that caused the error

https://c.tenor.com/rj9XIHQM1-8AAAAC/blues-brothers-2000.gif

### Steps to reproduce

1. type in @esmbot caption [text]
2. the error appears.

### Self-hosted instance?

No

### Error file

```
Message: WebAssembly.instantiate(): Out of memory: wasm memory

Stack Trace: undefined
```

### Additional context

it says something about memory
is there something related with my memory or the bot's memory or other?

**Comment by Mr-NI** [comment]
I have the same error

**Comment by meow6969** [comment]
Sex

**Comment by TheEssem** [comment]
Duplicate of #157
