### ISSUE TITLE
bot ran out of space

### ISSUE THREAD

**Issue by alexeyplayz** [esmBot/esmBot#190]
### Command that caused the error

@esmBot  caption It's a 50 NCR minimum to withdraw from your Neos wallet. I would recommend just finding someone you trust and selling it for paypal instead.

### Image that caused the error

Message: Magick: unable to extend cache '<span font_family="futura" weight="bold">It\<redacted>apos;s a 50 NCR minimum to withdraw from your Neos wallet. I would recommend just finding someone you trust and selling it for paypal instead.</span>': No space left on device @​ error/cache.c/OpenPixelCache/3900  Stack Trace: undefined

### Steps to reproduce

use the cap cmd 

### Self-hosted instance?

No

### Error file

```

```
[Uploading error.txt…]()

**Comment by TheEssem** [comment]
Seems there was something up with the system logs filling up a ton of space on one of the servers, should be fine now.
