### ISSUE TITLE
&caption error

### ISSUE THREAD

**Issue by deel72** [esmBot/esmBot#192]
### Command that caused the error

Command: &caption

### Steps to reproduce

1. Go to any server that has esmBot.
2. Send a gif/image
3. Type &caption

### Self-hosted instance?

No

### Error file

```
Message: Magick: unable to extend cache '': No space left on device @​ error/cache.c/OpenPixelCache/3900

Stack Trace: undefined
``

[error.txt](https://github.com/esmBot/esmBot/files/7614398/error.txt)
`


### Additional context

_No response_

**Comment by TheEssem** [comment]
Seems to have been cache-related, should be good to go now.
