### ISSUE TITLE
Dunno esmBot told me to report this idk what's happening tbh

### ISSUE THREAD

**Issue by ATSRO** [esmBot/esmBot#193]
### Describe the bug

[error.txt](https://github.com/esmBot/esmBot/files/7614404/error.txt)

### Self-hosted instance?

Yes

### Additional context

Bot stopped working and keeps sending error on every command

**Comment by ATSRO** [comment]
Ignore the steps to reproduce just use any cpmmand it will happen

**Comment by TheEssem** [comment]
Duplicate of #192
