### ISSUE TITLE
error when doing npm run build

### ISSUE THREAD

**Issue by KC080** [esmBot/esmBot#194]
whenever using npm run build, i always get this error.

Package Magick++ was not found in the pkg-config search path.
Perhaps you should add the directory containing `Magick++.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Magick++' found
gyp: Call to 'pkg-config --cflags Magick++' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\(name)\Desktop\Folders\esmBot-master\node_modules\node-gyp\lib\configure.js:259:16)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\(name)\\Desktop\\Folders\\esmBot-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build" "-j" "max"
gyp ERR! cwd C:\Users\(name)\Desktop\Folders\esmBot-master
gyp ERR! node -v v16.13.0
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok

**Comment by Xp-op** [comment]
You doesn't have Magick++ package

**Comment by meow6969** [comment]
u cant run esmbot on windows

**Comment by TheEssem** [comment]
> > You doesn't have Magick++ package
> 
> how can i download/install it? on windows btw

Win32 is not an officially supported platform. Please use [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install) to run the bot.

**Comment by KC080** [comment]
> > > You doesn't have Magick++ package
> > 
> > 
> > how can i download/install it? on windows btw
> 
> Win32 is not an officially supported platform. Please use [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install) to run the bot.

yeah but how do i download magick++

**Comment by meow6969** [comment]
if u are on windows u need to install windows subsystem for linux it is a sort of virtual machine that runs linux 
do that and then u can follow the normal steps in the setup guide to easily install magick++

**Comment by Xp-op** [comment]
> > > > You doesn't have Magick++ package
> > > 
> > > 
> > > how can i download/install it? on windows btw
> > 
> > Win32 is not an officially supported platform. Please use [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install) to run the bot.
> 
> yeah but how do i download magick++
> 

you need to build the magick++ from source

**Comment by Xp-op** [comment]
> if u are on windows u need to install windows subsystem for linux it is a sort of virtual machine that runs linux 
> do that and then u can follow the normal steps in the setup guide to easily install magick++

yeah this is better

**Comment by TheEssem** [comment]
> > > > You doesn't have Magick++ package
> > > 
> > > 
> > > how can i download/install it? on windows btw
> > 
> > Win32 is not an officially supported platform. Please use [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install) to run the bot.
> 
> yeah but how do i download magick++
> 

Follow the instructions here to download and build it from source: https://imagemagick.org/script/install-source.php

**Comment by KC080** [comment]
> > > > > You doesn't have Magick++ package
> > > > 
> > > > 
> > > > how can i download/install it? on windows btw
> > > 
> > > 
> > > Win32 is not an officially supported platform. Please use [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install) to run the bot.
> > 
> > 
> > yeah but how do i download magick++
> 
> Follow the instructions here to download and build it from source: https://imagemagick.org/script/install-source.php

im on wsl and i built it but whenever i do npm run build i get this error now

make: Entering directory '/mnt/c/Users/(name)/Desktop/Folders/esmBot-master/build'
  CXX(target) Release/obj.target/image/natives/blur.o
  CXX(target) Release/obj.target/image/natives/blurple.o
  CXX(target) Release/obj.target/image/natives/caption.o
  CXX(target) Release/obj.target/image/natives/caption2.o
  CXX(target) Release/obj.target/image/natives/circle.o
  CXX(target) Release/obj.target/image/natives/crop.o
  CXX(target) Release/obj.target/image/natives/deepfry.o
  CXX(target) Release/obj.target/image/natives/explode.o
../natives/blurple.cc:1:10: fatal error: Magick++.h: No such file or directory
    1 | #include <Magick++.h>
      |          ^~~~~~~~~~~~
../natives/circle.cc:1:10: fatal error: Magick++.h: No such file or directory
    1 | #include <Magick++.h>
      |          ^~~~~~~~~~~~
../natives/deepfry.cc:1:10: fatal error: Magick++.h: No such file or directory
    1 | #include <Magick++.h>
      |          ^~~~~~~~~~~~
../natives/blur.cc:1:10: fatal error: Magick++.h: No such file or directory
    1 | #include <Magick++.h>
      |          ^~~~~~~~~~~~
../natives/explode.cc:1:10: fatal error: Magick++.h: No such file or directory
    1 | #include <Magick++.h>
      |          ^~~~~~~~~~~~
../natives/crop.cc:1:10: fatal error: Magick++.h: No such file or directory
    1 | #include <Magick++.h>
      |          ^~~~~~~~~~~~
../natives/caption.cc:1:10: fatal error: Magick++.h: No such file or directory
    1 | #include <Magick++.h>
      |          ^~~~~~~~~~~~
../natives/caption2.cc:1:10: fatal error: Magick++.h: No such file or directory
    1 | #include <Magick++.h>
      |          ^~~~~~~~~~~~
compilation terminated.
compilation terminated.
compilation terminated.
compilation terminated.
compilation terminated.
compilation terminated.
compilation terminated.
compilation terminated.
make: *** [image.target.mk:169: Release/obj.target/image/natives/blur.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [image.target.mk:169: Release/obj.target/image/natives/blurple.o] Error 1
make: *** [image.target.mk:169: Release/obj.target/image/natives/caption.o] Error 1
make: *** [image.target.mk:169: Release/obj.target/image/natives/caption2.o] Error 1
make: *** [image.target.mk:169: Release/obj.target/image/natives/circle.o] Error 1
make: *** [image.target.mk:169: Release/obj.target/image/natives/crop.o] Error 1
make: *** [image.target.mk:169: Release/obj.target/image/natives/deepfry.o] Error 1
make: *** [image.target.mk:169: Release/obj.target/image/natives/explode.o] Error 1
make: Leaving directory '/mnt/c/Users/(name)/Desktop/Folders/esmBot-master/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/mnt/c/Users/(name)/Desktop/Folders/esmBot-master/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 4.4.0-19041-Microsoft
gyp ERR! command "/usr/bin/node" "/mnt/c/Users/(name)/Desktop/Folders/esmBot-master/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "-j" "max"
gyp ERR! cwd /mnt/c/Users/(name)/Desktop/Folders/esmBot-master
gyp ERR! node -v v16.13.1
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok
