### ISSUE TITLE
&image should be limited to channels marked NSFW

### ISSUE THREAD

**Issue by samhza** [esmBot/esmBot#198]
### Describe the bug

The command can be run in channels that aren't marked as NSFW and fetches images which may be NSFW.

### Steps to reproduce

Run the command in a channel that isn't marked as NSFW. The bot will allow you to run the command.

### Expected behavior

The command is not allowed to be ran in channels that aren't marked as NSFW.

### Screenshots

n/a

### Self-hosted instance?

No

### Additional context

Some users have reported bodies being sent by the bot in response to &image commands.

Top.gg does not allow bots to send NSFW content in channels not marked as NSFW.
> [Keep NSFW content (including, but not limited: links that source to pornographic material) inside of NSFW channels](https://support.top.gg/hc/en-us/articles/360059360894-Bot-Guidelines#:~:text=Keep%20NSFW%20content%20(including%2C%20but%20not%20limited%3A%20links%20that%20source%20to%20pornographic%20material)%20inside%20of%20NSFW%20channels)

**Comment by TheEssem** [comment]
If the image command sends NSFW on a normal search, that is considered a bug. I don't want anything to be intentionally NSFW im the bot.
