### ISSUE TITLE
Add a Damn Daniel soundboard command

### ISSUE THREAD

**Issue by poxut** [esmBot/esmBot#200]
### Describe the request

Make the funny bot say the funny line from Snapchat (Damn Daniel)
![image](https://user-images.githubusercontent.com/60271717/144948938-86276ba0-a0b7-4966-a16b-9d3e279d402f.png)

### Is your feature request related to a problem? Please describe.

There is no Damn Daniel command as of now, and I would like to have the one and only Joshua Holz saying the line in my Voice Chats at command.

### Additional context

It also seems that this meme has resurfaced with FlightReacts' video, so either an audio clip from Joshua's video or an audio clip from FlightReacts would still be pretty cool.

**Comment by TheEssem** [comment]
Implemented with #225, which has now been merged.
