### ISSUE TITLE
Can't disconnect or play music with the bot

### ISSUE THREAD

**Issue by SenketsuKLK** [esmBot/esmBot#201]
### Describe the bug

Message: TypeError: Cannot read properties of undefined (reading 'host')
    at StopCommand.run (file:///home/esmBot/esmBot/commands/music/stop.js?v=110:9:25)
    at default (file:///home/esmBot/esmBot/events/messageCreate.js:105:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Steps to reproduce

1st. type (prefix)disconnect
2nd. the error shows

### Expected behavior

I wanted to disconnect since the bot isn't listening to commands and not playing music

### Screenshots

![image](https://user-images.githubusercontent.com/96069171/145840097-e884e531-4867-4968-a7e3-474cffa25dae.png)

### Self-hosted instance?

No

### Additional context

Music will input but no sound is coming from the bot, and the commands are not functioning

**Comment by TheEssem** [comment]
This should (hopefully) be fixed with 382a7b0298b7a84d379d97c092ac2df56fdf04e6
