### ISSUE TITLE
Trying to caption gif but produces error

### ISSUE THREAD

**Issue by devxan** [esmBot/esmBot#206]
### Command that caused the error

?caption *cringe

### Image that caused the error

https://thumbs.gfycat.com/NearUnfoldedEft-max-1mb.gif

### Steps to reproduce

1. Use command "?caption" (prefix is ?) after posting image link in chat
2. Wait for bot to load
3. See error

### Self-hosted instance?

No

### Error file

```
Message: Magick: unable to extend cache '': No space left on device @​ error/cache.c/OpenPixelCache/3901

Stack Trace: undefined
```

### Additional context

<img width="551" alt="image" src="https://user-images.githubusercontent.com/57809064/147297812-acaf7656-e7ec-409f-bb0a-54c81c539651.png">
<img width="551" alt="image" src="https://user-images.githubusercontent.com/57809064/147297825-c3955589-4754-4208-b854-dec8ec1faf8f.png">

**Comment by TheEssem** [comment]
Seems that the server was running out of temp space. The issue itself was fixed, but unfortunately that can't be seen now due to the Discord ban.
