### ISSUE TITLE
Too much stolen code

### ISSUE THREAD

**Issue by ghost** [esmBot/esmBot#21]
You are a paranoid schizo. You are a paranoid schizo. You are a paranoid schizo. You are a paranoid schizo. You are a paranoid schizo. You are a paranoid schizo.

**Comment by supermarioworldjazz** [comment]
[https://media.discordapp.net/attachments/625178994911739915/772417918062821396/yhee.PNG](url)

**Comment by supermarioworldjazz** [comment]
Squidward... Tortellini?
