### ISSUE TITLE
Bot becomes unresponsive when trying to stop playing music and exit vc

### ISSUE THREAD

**Issue by BosnianSpy** [esmBot/esmBot#210]
### Command that caused the error

&stop

### Steps to reproduce

1. type "&stop" in a text channel when in a voice channel with the bot

### Self-hosted instance?

No

### Error file

Message: TypeError: Cannot read properties of undefined (reading 'host')
    at StopCommand.run (file:///home/esmBot/esmBot/commands/music/stop.js?v=112:9:25)
    at default (file:///home/esmBot/esmBot/events/messageCreate.js:105:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Additional context

tried to get the bot to stop playing music and leave the vc, instantly became unresponsive and posted an error message 29 minutes later

**Comment by BosnianSpy** [comment]
By "becomes unresponsive", I mean that the bot did not respond to any commands and did not take any action.

**Comment by TheEssem** [comment]
Seems to be fixed with fb0c8ffae17557b5249b4039b81ccf43a58050e6.
