### ISSUE TITLE
Message: Request ended prematurely due to a closed connection Stack Trace: undefined

### ISSUE THREAD

**Issue by ItsMTVGD** [esmBot/esmBot#211]
### Describe the bug

&caption when esmbot takes too long when the when the when the sus (Trigger)

Message: Request ended prematurely due to a closed connection(Error)

Stack Trace: undefined

### Expected behavior

To display a caption when esmbot takes too long when the when the when the sus

### Screenshots

No

### Self-hosted instance?

Yes

### Additional context

No

**Comment by TheEssem** [comment]
Check the image API logs, are there any errors in there?

**Comment by TheEssem** [comment]
Closing until OP responds.
