### ISSUE TITLE
Request to URL failed, reason: getaddrinfo EAI_AGAIN

### ISSUE THREAD

**Issue by cantnot** [esmBot/esmBot#212]
### Command that caused the error

&meme

### Image that caused the error

https://media.discordapp.net/attachments/834923061413150723/925831010879410226/illust_95113601_20211229_181102.jpg

### Steps to reproduce

replied to an image I tried to meme when the bot was offline
copied the command I tried to run and pasted it in the reply
bot gave me the error with the file telling me I should report it

### Self-hosted instance?

Yes

### Error file

in error.txt I got:
Message: request to https://media.discordapp.net/attachments/834923061413150723/925831010879410226/illust_95113601_20211229_181102.jpg failed, reason: getaddrinfo EAI_AGAIN media.discordapp.net

Stack Trace: undefined

**Comment by cantnot** [comment]
I only get this error if I type spicificly "&meme you should kill yourself,now" I tried the &meme command on other images and it seems to be working just fine

**Comment by TheEssem** [comment]
Seems like a network issue, considering you're using a self-hosted version of the bot. I'd suggest checking the network connection of the server you're running it off of.
