### ISSUE TITLE
Magick: unable to read pixel cache: file exists

### ISSUE THREAD

**Issue by bigolthorny** [esmBot/esmBot#221]
command that caused the issue:
uncaption

image that caused the error

https://tenor.com/view/epic-gif-19624336

steps to reproduce
1: post image in any channel
2: do uncaption command

error file:
[error.txt](https://github.com/esmBot/esmBot/files/7917715/error.txt)

**Comment by TheEssem** [comment]
Will be fixed when #290 is resolved

**Comment by TheEssem** [comment]
This issue does not seem to be occurring on the main instance anymore, closing.
