### ISSUE TITLE
change captioning error when there's no file to caption

### ISSUE THREAD

**Issue by Klanker** [esmBot/esmBot#223]
### Describe the request

change the text from
"You need to provide an image to add a caption!"
to
"You need to provide an image/GIF to add a caption!"
so people'd know you can use it on gifs as well

**Comment by TheEssem** [comment]
This is how it used to be, actually; I removed the GIF part originally to attempt to be more general, but it seems like animation support could be lost on some people this way. Don't really see much harm in reverting it back tbh

**Comment by TheEssem** [comment]
Changed with 7248621
