### ISSUE TITLE
&play cannot play links wrapped in <>

### ISSUE THREAD

**Issue by uncountablemeaning** [esmBot/esmBot#226]
### Describe the bug

Whenever &play is sent with a url that's wrapped in <> symbol (to remove the embed) it will not play the song and says it "cannot find it"

### Steps to reproduce

- send (as an example) &play <https://www.youtube.com/watch?v=Ns3YxbIhTRM>

### Expected behavior

the bot plays the video normally

### Screenshots

![image](https://user-images.githubusercontent.com/92690709/151274940-dc5317e3-a738-4f2a-874e-51e8b7b81d43.png)
![image](https://user-images.githubusercontent.com/92690709/151275073-a26adf80-380b-46ff-9d0b-fdd0cad86432.png)

### Self-hosted instance?

No

**Comment by TheEssem** [comment]
Fixed in eca5c58, should be out soon
