### ISSUE TITLE
&caption failing, Magick unable to extend cache

### ISSUE THREAD

**Issue by hrtowii** [esmBot/esmBot#231]
### Command that caused the error

,caption [my chem teacher suddenly screaming during practical and giving me a heart attack (i spilled acid over my hands) (my paper is wet)] https://imgur.com/a/1l1auFe

### Image that caused the error

https://imgur.com/a/1l1auFe

### Steps to reproduce

call &caption

### Self-hosted instance?

No

### Error file

```

Message: Magick: unable to extend cache '': No space left on device @​ error/cache.c/OpenPixelCache/3900  
Stack Trace: undefined

```

### Additional context

r/whenthe server

**Comment by TheEssem** [comment]
Server-side issue, should be fixed now
