### ISSUE TITLE
Erroring on gifs

### ISSUE THREAD

**Issue by konn-neko** [esmBot/esmBot#234]
### Command that caused the error

any of the image editing commands

### Image that caused the error

any gif

### Steps to reproduce

1. Get a gif from tennor
2. run any editing command like caption, flip, etc
3. hope it works
4. error in chat
tenor

### Self-hosted instance?

Yes

### Error file

```
Message: Magick: no decode delegate for this image format `​' @​ error/blob.c/BlobToImage/458

Stack Trace: undefined
```

### Additional context

it works on nomral images but gifs from tennor error

**Comment by TheEssem** [comment]
You'll need to get an API key from Tenor [over here](https://tenor.com/developer/keyregistration) and put it in `.env` as the `TENOR` variable.
