### ISSUE TITLE
Only works with gifs

### ISSUE THREAD

**Issue by French-Cat** [esmBot/esmBot#235]
### Command that caused the error

all

### Image that caused the error

anything other than gifs

### Steps to reproduce

1. try any command on non gif
2. wait for output
3. returns error

### Self-hosted instance?

Yes

### Error file

```
Message: Magick: no decode delegate for this image format `​' @​ error/blob.c/BlobToImage/458

Stack Trace: undefined
```

**Comment by TheEssem** [comment]
Can you run `magick -version` and post the output?

**Comment by TheEssem** [comment]
Closing until OP responds.
