### ISSUE TITLE
[2022-02-20 10:13:26]: [ERROR] - Cluster 0 | SQLite migration failed: SqliteError: no such table: guilds

### ISSUE THREAD

**Issue by ah-yis** [esmBot/esmBot#236]
I am trying to host the bot on my own PC because the original one is very slow, but I'm getting a problem when I run `npm start`.
I have attached the output as a .txt file under attachments, please see that.
And yes, I did follow the [Self Hosting Guide](https://github.com/esmBot/esmBot/wiki/Setup), and I am using WSL on Windows 11.

The 3 errors in the output are:
`[2022-02-20 10:13:25]: [ERROR] - Cluster 0 | Failed to get status of Lavalink node localhost.`
`[2022-02-20 10:13:26]: [ERROR] - Cluster 0 | SQLite migration failed: SqliteError: no such table: guilds`
`[2022-02-20 10:13:26]: [ERROR] - Cluster 0 | Unable to start the bot, quitting now.`
[esmBot-Terminal Output.txt](https://github.com/esmBot/esmBot/files/8103569/esmBot-Terminal.Output.txt)

Please help me with this, thanks!

**Comment by TheEssem** [comment]
Should be fixed with 4ef2ce7.
