### ISSUE TITLE
Errors keep on occurring when I try to use the commands "Caption, Caption2, Motivate"

### ISSUE THREAD

**Issue by ARandomDeeto** [esmBot/esmBot#24]
[error (1).txt](https://github.com/esmBot/esmBot/files/5561250/error.1.txt)
This was the error I recieved.

**Comment by TheEssem** [comment]
What image and command parameters were used? If you're running the bot instance that this is happening on, is the version of ImageMagick used on the instance built with support for Pango?

**Comment by TheEssem** [comment]
Closing since OP never gave a response. Will reopen if they reply to this issue.
