### ISSUE TITLE
&caption command error

### ISSUE THREAD

**Issue by eth3realze** [esmBot/esmBot#250]
### Describe the bug

so when i tried to use the &caption command, it errors and idk if it's a bug or an error

### Steps to reproduce

1. choose a gif first, then send
2. then use &caption with text
3. didn't respond
4. but a few hours later, I got an error text?

### Expected behavior

i expect this behavior to become successful with the captioned gif

### Screenshots

![error oof](https://user-images.githubusercontent.com/101610057/158287800-ddafe076-ae1d-43c6-b79e-53d5b1ac6b80.JPG)

### Self-hosted instance?

Yes

### Additional context

nope. *just hoping this command works

**Comment by bjcscat** [comment]
bot having problems

**Comment by TheEssem** [comment]
Looks like some server-side latency/network issues, most likely the Discord API was being slow at that time
