### ISSUE TITLE
EsmBot is down? WHY?!

### ISSUE THREAD

**Issue by te-agma-at** [esmBot/esmBot#254]
### Describe the bug

EsmBot does not reply when attempting to run a command.

### Steps to reproduce

1. Post a command in any channel with EsmBot in the server
2. Watch EsmBot stop responding

### Expected behavior

Replies to commands with result

### Screenshots

![image](https://user-images.githubusercontent.com/72958435/161442447-8baeb23d-f2a8-4a40-8b5d-5ce1814bc101.png)
esmbot down

### Self-hosted instance?

No

**Comment by User9684** [comment]
ah yes

**Comment by TheEssem** [comment]
There's been quite a few image server latency issues, those should be fixed once the code in https://github.com/esmBot/azure-function-wrapper goes live

**Comment by Tails1402** [comment]
EsmBot pulled up an error for the &ssbu command how do i even get it to work
[error.txt](https://github.com/esmBot/esmBot/files/8836191/error.txt)

**Comment by meiusern** [comment]
why you never take image for explode

**Comment by TheEssem** [comment]
Slash commands pretty much give a response whether the bot actually responds or not, so I'm closing this issue for now. Check #301 and #310 instead if you're having this issue with slash commands.
