### ISSUE TITLE
It told me to report this error here

### ISSUE THREAD

**Issue by CarlosRollo** [esmBot/esmBot#255]
### Describe the bug

Message: Magick: zero-length blob not permitted `​' @​ error/blob.c/BlobToImage/446

Stack Trace: undefined

### Self-hosted instance?

No

**Comment by samhza** [comment]
What image/command did you use?

**Comment by CarlosRollo** [comment]
https://cdn.discordapp.com/attachments/846298836301643776/963075225212309554/IMG_20220411_155425.jpg
&caption srasz

**Comment by TheEssem** [comment]
Duplicate of #238
