### ISSUE TITLE
Message: Magick: unable to write pixel cache '/tmp/magick-6SUJ3ZiU6mI13INWrIJHhDo5AGI5FeLl': No space left on device @​ error/cache.c/WritePixelCachePixels/5845  Stack Trace: undefined

### ISSUE THREAD

**Issue by JustAPerson24** [esmBot/esmBot#258]
### Command that caused the error

.caption

### Image that caused the error

https://tenor.com/view/xqcbozo-xqc-smoking-smoking-pack-smoke-pack-gif-25157451

### Self-hosted instance?

Yes

### Error file

Message: Magick: unable to write pixel cache '/tmp/magick-6SUJ3ZiU6mI13INWrIJHhDo5AGI5FeLl': No space left on device @​ error/cache.c/WritePixelCachePixels/5845

Stack Trace: undefined

### Additional context

N/A

**Comment by TheEssem** [comment]
Server-side issue, fixed now
