### ISSUE TITLE
What is the image.node file?

### ISSUE THREAD

**Issue by Mysterious-Brickhead** [esmBot/esmBot#26]
IN the image.js code theres a file that it requires titled 'build/release/image.node' It keeps saying I dont have that file, what exactly is the file?

**Comment by TheEssem** [comment]
The file is the result of building the native image code. Make sure to run `npm run build` to generate it.

**Comment by Mysterious-Brickhead** [comment]
I tried generating it, however i keep getting this error C:\Users\(classified)\Documents\esmBot-master>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure build )
'pkg-config' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to 'pkg-config --cflags Magick++' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\(classified)\Documents\esmBot-master
gyp ERR! node -v v12.18.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! esmbot@1.3.3 build: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the esmbot@1.3.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\(classified)\AppData\Roaming\npm-cache\_logs\2020-12-02T22_06_56_137Z-debug.log

**Comment by samhza** [comment]
You don't have pkg-config installed.

**Comment by TheEssem** [comment]
Running the bot on pure Windows is a bit of a hassle due to many needed tools not being easily obtainable, as is the case with pkg-config here

I’d recommend using Windows Subsystem for Linux or something similar instead

**Comment by Mysterious-Brickhead** [comment]
How do I install pkg-config, is it a node package? im confused.

**Comment by TheEssem** [comment]
> How do I install pkg-config, is it a node package? im confused.

It’s a piece of software used alongside compilers like GCC to find/link libraries, pretty sure there isn’t a Windows version however so you’ll have to use WSL
