### ISSUE TITLE
error in &cat command

### ISSUE THREAD

**Issue by gongas2346** [esmBot/esmBot#260]
### Command that caused the error

&cat

### Self-hosted instance?

No

### Error file

```
Message: {
  code: 50035,
  message: 'Invalid Form Body\n  embeds.0.description: This field is required',
  name: 'DiscordRESTError [50035]',
  stack: 'DiscordRESTError [50035]: Invalid Form Body\n' +
    '  embeds.0.description: This field is required\n' +
```

### Additional context

when I put the command &cat it gives an error

**Comment by TheEssem** [comment]
The server that the cat images were hosted on went down for a bit. It should be back up now.
