### ISSUE TITLE
Detect when a Spotify link is being passed to the play command and search the title of the song on YouTube or Soundcloud, and play that instead.

### ISSUE THREAD

**Issue by IoIxD** [esmBot/esmBot#262]
### Describe the request

Apparently many other music bots solve the Spotify issue (that being that you legally and legitimately cannot play Spotify songs through any API) by just getting the song title (probably through the embed, but I think Spotify at least has a rudementary API that lets you get the song title) and passes it to ytsearch, and plays that instead. I don't personally care about this but a friend of mine without an account wants to see this added, so I'm making a feature request for this on his behalf.

**Comment by TheEssem** [comment]
This Lavalink plugin adds support for Spotify and Apple Music, could probably add it to the example `application.yml` file: https://github.com/Topis-Lavalink-Plugins/Topis-Source-Managers-Plugin

**Comment by teo0781** [comment]
I've tested the plugin solution, either i haven't configured it properly, or it doesn't work with the current code, i'm guessing it must be modified to add support for the `spsearch` command, although i'm not very experienced so i may be saying something completely wrong.

**Comment by TheEssem** [comment]
> I've tested the plugin solution, either i haven't configured it properly, or it doesn't work with the current code, i'm guessing it must be modified to add support for the `spsearch` command, although i'm not very experienced so i may be saying something completely wrong.

What Lavalink version are you on? Plugin support isn't included in any release builds yet, you'll need to use the dev branch builds.

**Comment by teo0781** [comment]
> > I've tested the plugin solution, either i haven't configured it properly, or it doesn't work with the current code, i'm guessing it must be modified to add support for the `spsearch` command, although i'm not very experienced so i may be saying something completely wrong.
> 
> What Lavalink version are you on? Plugin support isn't included in any release builds yet, you'll need to use the dev branch builds.


The lavalink version you include in the self-hosting guide, and it seems to have plugin support as it seems to recognize, I may be wrong though.

**Comment by TheEssem** [comment]
Addressed with 274f11b, you'll need a recent Lavalink and Spotify API keys.
