### ISSUE TITLE
Incredibox motivate

### ISSUE THREAD

**Issue by UsernameNoIdeas** [esmBot/esmBot#263]
### Command that caused the error

&motivate Incredibox

### Steps to reproduce

Type &motivate Incredibox
Wait

### Self-hosted instance?

No

### Error file

```
Message: Magick: zero-length blob not permitted `​' @​ error/blob.c/BlobToImage/446

Stack Trace: undefined
```

**Comment by TheEssem** [comment]
Duplicate of #238
