### ISSUE TITLE
Caption Error

### ISSUE THREAD

**Issue by MRL1002** [esmBot/esmBot#266]
### Command that caused the error

&caption

### Image that caused the error

https://media.discordapp.net/attachments/347254691966615552/973892752528007178/ml668gawvbk81.gif

### Steps to reproduce

1. type &caption
2. wait

### Self-hosted instance?

Yes

### Error file

Message: Magick: unable to write pixel cache '/tmp/magick-i929Bj8HwfdeDzQp8leM_xB29RmDs18l': No space left on device @​ error/cache.c/WritePixelCachePixels/5845

Stack Trace: undefined

**Comment by bjcscat** [comment]
consider the following:

no space left on device

**Comment by TheEssem** [comment]
Server-side issues happened, they were taken care of.
