### ISSUE TITLE
&speechbubble command

### ISSUE THREAD

**Issue by R3Ked** [esmBot/esmBot#267]
### Describe the request

I'd like the bot to be able to generate a speech bubble meme when you give it an image with this command.

### Additional context

It would look like one of these
![speechbubble](https://user-images.githubusercontent.com/20342336/168446522-1e19135b-65db-4968-adc5-2cbb69dbf27e.PNG)

**Comment by bjcscat** [comment]
This already exists, just not on the main bot yet

**Comment by TheEssem** [comment]
This is already a feature in the main branch as of commit b17611917f3b785d0a470060fb860ab7bc4521b5.
