### ISSUE TITLE
&caption request timed out: undefined stack trace.

### ISSUE THREAD

**Issue by JoolthePlanet** [esmBot/esmBot#268]
### Command that caused the error

&caption Bruh

### Image that caused the error

https://giphy.com/gifs/void-black-hole-blackhole-PkKzNQjwPy7GvxZbfe

### Steps to reproduce

1. https://giphy.com/gifs/void-black-hole-blackhole-PkKzNQjwPy7GvxZbfe
2. &caption Bruh

### Self-hosted instance?

No

### Error file

Message: Request timed out (>30000ms)

Stack Trace: undefined

**Comment by TheEssem** [comment]
Duplicate of #138
