### ISSUE TITLE
Error captioning GIF

### ISSUE THREAD

**Issue by TacoBoyVR** [esmBot/esmBot#271]
### Command that caused the error

&caption

### Image that caused the error

https://tenor.com/view/gif-25830057

### Steps to reproduce

1. Post GIF in chat
2. Post "&caption blablabla"
3. Wait at least 1-20 minutes

### Self-hosted instance?

Yes

### Error file

Message: Magick: zero-length blob not permitted `​' @​ error/blob.c/BlobToImage/446

Stack Trace: undefined

**Comment by TheEssem** [comment]
You'll need a Tenor API key from here if you wish to use Tenor GIFs, or else it will throw that error: https://tenor.com/developer/keyregistration
