### ISSUE TITLE
caption didn't work on gif

### ISSUE THREAD

**Issue by plonzz** [esmBot/esmBot#273]
### Command that caused the error

&caption i shit myself

### Image that caused the error

https://tenor.com/view/hololive-hakos-baelz-holo-en-rat-gif-23656957

### Steps to reproduce

1. Post gif (https://tenor.com/view/hololive-hakos-baelz-holo-en-rat-gif-23656957).
2. Type: '&caption i shit myself'
3. error time

### Self-hosted instance?

Yes

### Error file

Message: request to http://<redacted>:3762/image?id=8096 failed, reason: read ECONNRESET

Stack Trace: undefined

**Comment by teo0781** [comment]
You've got the API enabled in your config, are you sure you want to be using it? It's not necessary.
You're also missing the API url.

**Comment by TheEssem** [comment]
Seems like the external image API is enabled but you're not running an instance of it, edit your `.env` and set `API=false`.
