### ISSUE TITLE
&caption adds a "\" before &apos

### ISSUE THREAD

**Issue by EternalRisen** [esmBot/esmBot#274]
### Describe the bug

when using &caption and using an apostrophe or any other form of that that isn't alphanumeric it will put an `\` before the non-alphanumeric char, likely due to something with how the strings are being handled.

### Steps to reproduce

use &caption on an image and have the caption text arg have an apostrophe

### Expected behavior

caption should not be `\'` but `'`

### Screenshots

![image](https://user-images.githubusercontent.com/56415221/173161693-653338f6-b389-4a4b-b57d-54fc0c3c8d7c.png)

### Self-hosted instance?

No

**Comment by Gcat101** [comment]
" too

**Comment by TheEssem** [comment]
The main instance is using a mix of ImageMagick and libvips servers at the moment, both of which use different methods of text processing. The next update (which will release very soon) will move all of the servers to libvips and end up fixing the issue.

**Comment by TheEssem** [comment]
Fixed on the main instance.
