### ISSUE TITLE
PNG/JPEG/etc to GIF command

### ISSUE THREAD

**Issue by veast-network** [esmBot/esmBot#277]
### Describe the request

Title. Basically a image to GIF command so you can easily favorite the GIF. For example having a speechbubble image and being able to favorite it so you can send it quickly.

**Comment by djtravz** [comment]
this is an awesome idea

**Comment by dd-pardal** [comment]
GIF is a horrible format. If you convert an image to GIF, you loose a lot of quality. It's not as convenient, but I suggest you save the images in a folder so you can upload them easily when you want to.

**Comment by veast-network** [comment]
it isn't that bad, and I don't think you would need extremely high quality
on a image that has a speechbubble on it

**Comment by djtravz** [comment]
It only really needs to be like 500px for what I'm picturing
Almost like a free way to send stickers

**Comment by bjcscat** [comment]
I might do this

**Comment by TheEssem** [comment]
Duplicate of #242, feel free to continue discussion there.
