### ISSUE TITLE
pixelate didn't work after df

### ISSUE THREAD

**Issue by sirogameminh** [esmBot/esmBot#278]
### Command that caused the error

&pixelate

### Image that caused the error

https://cdn.discordapp.com/attachments/986296740699328624/988412171748802560/deepfry.gif

### Self-hosted instance?

Yes

### Error file

Message: VipsRegion: valid clipped to nothing
VipsRegion: valid clipped to nothing
VipsRegion: valid clipped to nothing
VipsRegion: valid clipped to nothing
VipsRegion: valid clipped to nothing
VipsRegion: valid clipped to nothing

### Additional context

bug
error

**Comment by TheEssem** [comment]
Looks like a rounding issue, should be fixed by 3d2a8f2
