### ISSUE TITLE
&caption doesnt support UTF-8 / Unicode

### ISSUE THREAD

**Issue by J0w03L** [esmBot/esmBot#29]
Attempting to use any non-ascii characters with &caption results in this:

`Message: magick: geometry does not contain image '/tmp/magick-56T0hgI2ZJorLI6XXaRWEgs--pLsOxNM' @ warning/attribute.c/GetImageBoundingBox/510.

Stack Trace: undefined`

**Comment by TheEssem** [comment]
Already fixed with 0600cf2, should make it into the main bot when 1.4 is stable (which is hopefully soon™)
