### ISSUE TITLE
/dice error

### ISSUE THREAD

**Issue by cherryredchariot** [esmBot/esmBot#296]
### Command that caused the error

/dice max:2

### Steps to reproduce

1) type /dice max:2
then error appeared

### Self-hosted instance?

No

### Error file

```
Message: Error: connect ECONNREFUSED ::1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1237:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 5432
}

Stack Trace: Error: connect ECONNREFUSED ::1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1237:16)
```

**Comment by Milan21y** [comment]
same thing happened to me while trying to execute basically any command

Message: Error: connect ECONNREFUSED ::1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1237:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',

**Comment by devcey** [comment]
I got the same exact error message. Is esmBot perhaps down right now?

**Comment by gvnfc3** [comment]
its a known issue, owners are fixing it

**Comment by TheEssem** [comment]
Seems like the database crashed for whatever reason, should be fixed now.
