### ISSUE TITLE
avatar command not working

### ISSUE THREAD

**Issue by sentrymodman** [esmBot/esmBot#297]
it doesnt work
message:
Message: Error: connect ECONNREFUSED ::1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1237:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 5432
}

Stack Trace: Error: connect ECONNREFUSED ::1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1237:16)

**Comment by gvnfc3** [comment]
its a known issue, owners are fixing it

**Comment by TheEssem** [comment]
See [this comment](https://github.com/esmBot/esmBot/issues/296#issuecomment-1186573704)
