### ISSUE TITLE
&caption not working

### ISSUE THREAD

**Issue by NightHnh099** [esmBot/esmBot#298]
### Command that caused the error

&caption

### Steps to reproduce

I just used the &caption command on an image as it was intended and the bot replied with an error log.

### Self-hosted instance?

No

### Error file

```
Message: Error: connect ECONNREFUSED ::1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1237:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 5432
}

Stack Trace: Error: connect ECONNREFUSED ::1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1237:16)
```

**Comment by gvnfc3** [comment]
its a known bug right now, the owners are trying to fix it

**Comment by TheEssem** [comment]
See [this comment](https://github.com/esmBot/esmBot/issues/296#issuecomment-1186573704)
