### ISSUE TITLE
nothing working

### ISSUE THREAD

**Issue by 197618** [esmBot/esmBot#299]
literally nothing is working

**Comment by jaekyle122** [comment]
Yeah, I experienced this issue too. No command is working, not even &help
<img width="481" alt="Screenshot 2022-07-17 085446" src="https://user-images.githubusercontent.com/88638460/179407225-b0d318e1-9ec2-43bd-abf0-23ec5dace968.png">
.

**Comment by TheEssem** [comment]
See [this comment](https://github.com/esmBot/esmBot/issues/296#issuecomment-1186573704), also in most cases please be more descriptive with issue reports.
