### ISSUE TITLE
Problem on esmbot 

### ISSUE THREAD

**Issue by noubanim** [esmBot/esmBot#30]
![F64D38D4-3949-46AF-8868-1DFED5D66416](https://user-images.githubusercontent.com/76239677/102693204-90a1cc80-41de-11eb-8035-437d77d85160.png)
Every time I put &speed or &caption it give me this 0 gb am I doing it wrong?

**Comment by TheEssem** [comment]
Seems to be related to the server's OOM-killer taking effect and stopping the image process before it can finish. Protections have been applied on the master branch, however for now you should be able to wait a bit and run the command again.
