### ISSUE TITLE
&Caption Failed

### ISSUE THREAD

**Issue by Kisenburger** [esmBot/esmBot#300]
### Command that caused the error

&caption balls

### Self-hosted instance?

No

### Error file

```
Message: Error: connect ECONNREFUSED ::1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1237:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
```

**Comment by TheEssem** [comment]
See [this comment](https://github.com/esmBot/esmBot/issues/296#issuecomment-1186573704)
