### ISSUE TITLE
Motivate command crashes with a comma

### ISSUE THREAD

**Issue by Hd28br** [esmBot/esmBot#306]
### Command that caused the error

&motiv ,

### Steps to reproduce

1. Get any image
2. Run `&motiv ,`
3. Done

### Self-hosted instance?

No

### Error file

```
Message: text: no text to render


Stack Trace: undefined
```

### Additional context
My fix ideas:
1. Add a way to render empty text
2. Block users from putting just a comma

![image](https://user-images.githubusercontent.com/52140269/182277057-fef12abd-03dd-44aa-8981-9051e3f89065.png)

**Comment by TheEssem** [comment]
Should be fixed with 4265e3e914bfe51798de7d7a9659cf876ca4a049
