### ISSUE TITLE
All commands run into an error

### ISSUE THREAD

**Issue by gemsoundscool** [esmBot/esmBot#307]
### Command that caused the error

/caption , /implode

### Steps to reproduce

1a. Type in /caption
2. put in text and image
3. error occurs

1b. Type in /implode
2. Insert image
3. error occurs

### Self-hosted instance?

Yes

### Error file

[error.txt](https://github.com/esmBot/esmBot/files/9292175/error.txt)

**Comment by TheEssem** [comment]
Seems to have been a remnant of some debugging stuff on the main server, should be fixed now.
