### ISSUE TITLE
Can't escape strings in slash commands

### ISSUE THREAD

**Issue by aubymori** [esmBot/esmBot#312]
### Describe the bug

You used to be able to use a backslash to escape characters, but since Discord introduced the awful slash commands system, that doesn't work anymore.

### Steps to reproduce

Try to make any caption image with a character you need to escape.

### Expected behavior

You should be able to escape characters.

### Screenshots

![image](https://user-images.githubusercontent.com/44238627/189239697-533682f7-d5a0-4f35-82ca-168347b2c953.png)

### Self-hosted instance?

No

### Additional context

Like in the screenshot, this bug means you can't put any emoji names in the caption without actually rendering the emoji.

**Comment by TheEssem** [comment]
Should be addressed by 3eae453de365c7e657c8cce40054b9c3092c80ee
