### ISSUE TITLE
error report from the bot when i post /caption

### ISSUE THREAD

**Issue by miranyafuz** [esmBot/esmBot#316]
### Command that caused the error

i typed /caption and the bot says uh oh i ran into a error

### Image that caused the error

https://discord.com/channels/1019216080301989898/1019283364437557250/1028999041364791307

### Steps to reproduce

3. Scroll down to '.....'

### Self-hosted instance?

Yes

### Error file

```

```

### Additional context

i dont know what to say here

**Comment by TheEssem** [comment]
The image is inaccessible and you didn't post the error file. Not much I can do here.
