### ISSUE TITLE
PostgreSQL migration failed: ... column "broadcast" of relation "settings" already exists

### ISSUE THREAD

**Issue by Naftoreiclag** [esmBot/esmBot#319]
### Describe the bug

I was setting up esmBot to use PostgreSQL, by following [the steps here](https://esmbot.github.io/esmBot/postgresql/). The bot gives an error saying it cannot run its version 3 update script for PostgreSQL:

```
[WARN] - Migrating PostgreSQL database, which is currently at version 2...
[WARN] - Running version 3 update script (ALTER TABLE settings ADD COLUMN broadcast text)...
[ERROR] - PostgreSQL migration failed: PostgresError: column "broadcast" of relation "settings" already exists
[ERROR] - Unable to start the bot, qutting now.
```

My current workaround is to delete the problematic column by running this in `psql` manually:

```
esmbot=> ALTER TABLE settings DROP COLUMN broadcast;
ALTER TABLE
```

This works fine for me since I am doing a fresh install, and do not have any data that needs to be preserved. However, this is a bug that others will also run into.

### Steps to reproduce

1. Start installing esmBot by following the steps [listed here](https://esmbot.github.io/esmBot/setup/). During 4 in the setup guide, choose to set up PostgreSQL as [described here](https://esmbot.github.io/esmBot/postgresql/).
3. Finish the rest of the setup guide, and launch the bot.
4. See the error.

### Expected behavior

Since I did not have any existing data, the database migrations should have been able to run automatically.

### Self-hosted instance?

Yes

### Additional context

I was doing a fresh PostgreSQL install too, so there should not have been any prior databases interfering with esmBot.

**Comment by TheEssem** [comment]
Should be fixed by fa3d7b37726a9f8690b919f8dc1b4603091b8bf8.
