### ISSUE TITLE
The bot deadass doesn't reply 💀

### ISSUE THREAD

**Issue by asthmall** [esmBot/esmBot#321]
### Describe the bug

Whether I use the prefix or ping the bot it does not reply.

### Steps to reproduce

1. Send gif
2. Do command to caption said gif
3. Don't get a reply

### Expected behavior

1. Send gif
2. Do command to caption said gif
3. Get the captioned gif

### Self-hosted instance?

No

**Comment by TheEssem** [comment]
Are you using slash commands or the old prefix-style commands? The main bot only accepts slash commands now due to Discord policy and API changes.
