### ISSUE TITLE
esmBot not responding to any command.

### ISSUE THREAD

**Issue by parrxtkun** [esmBot/esmBot#322]
### Describe the bug

When I try to do literally anything with the bot it doesn't work.
It just says "The application did not respond." when I try to run any command.

### Steps to reproduce

1. do literally any command
2. wait a few seconds
3. it will show a message that says "The application did not respond."
note: i only found and tried this in DMs so the bug may not work in servers.

### Expected behavior

I expected the commands to work as intended but none of them responded.

### Screenshots

![image](https://user-images.githubusercontent.com/93410491/199081724-a09fbc3c-e572-4e28-8e5a-19a9a4d3c444.png)
(Here's a screenshot of the message)
![image](https://user-images.githubusercontent.com/93410491/199082140-b2636bdc-614b-4487-95c5-a9474adfafc0.png)
(I also managed to get a screenshot of a command loading.)

### Self-hosted instance?

No

### Additional context

Again, I only tried this in DMs so it might work in servers.

**Comment by teo0781** [comment]
Known. Server is migrating to new version.

**Comment by parrxtkun** [comment]
oh thanks
