### ISSUE TITLE
Mka files with mp3 as the audio codec aren't recognized by music command

### ISSUE THREAD

**Issue by Niterux** [esmBot/esmBot#329]
### Describe the bug

Using /music play for a file url that uses the mka container but the mp3 codec will make the bot say "I couldn't find that song!" While .mka files with opus audio and regular .mp3 files can play fine

### Steps to reproduce

1. Upload a .mka file with mp3 audio codec
2. Use the /music play to attempt to play it
3. Bot will say "I couldn't find that song!"

### Expected behavior

Bot adds the file to the queue successfully

### Screenshots

![Screenshot_2022-11-18-18-49-49-935](https://user-images.githubusercontent.com/110568869/202821650-1bfdcb56-4bce-4c9f-804b-1e2adf97faa5.jpeg)
(First file is mka with mp3 codec, 2nd file is plain mp3)

### Self-hosted instance?

No

### Additional context

Haven't tested with other codecs, all I know mp3 doesn't work and opus does when in .mka container, and that .mp3 files also work

**Comment by TheEssem** [comment]
Format support is handled by Lavalink, which does not seem to support Matroska at the moment. I'd suggest creating an issue for mkv/mka support over there instead: https://github.com/freyacodes/Lavalink
