### ISSUE TITLE
/music play "Waiting for someone to return" bug

### ISSUE THREAD

**Issue by jedddg** [esmBot/esmBot#346]
### Describe the bug

When I leave the VC, it says the message "Waiting for someone to return", although when I return the VC it does not continue the music session.

### Steps to reproduce

1. Join a voice channel
2. Run /music play and pick any song
3. Leave the VC and join it again
4. Bot says "The voice channel in General has ended"

### Expected behavior

I expect it to continue the player like normal.

### Screenshots

![Uploading image.png…]()

### Self-hosted instance?

No

### Additional context

This is probably an Oceanic.JS issue

**Comment by TheEssem** [comment]
Looks related to #327, and after some investigation it does indeed look like an upstream issue. I've brought it up and it seems like it should be fixed soon.

**Comment by TheEssem** [comment]
The pull request above was merged and the bot has been updated to Oceanic 1.5.1, which contains the fix.

**Comment by ljcool2006** [comment]
This is still an issue, this occurred to me today.

**Comment by TheEssem** [comment]
> This is still an issue, this occurred to me today.

Seeing as the specific bug here was fixed, I'd suggest creating a new issue.
