### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by DUCKONAROLL** [esmBot/esmBot#347]
### Describe the bug

Apologies if this is not where this issue goes

https://docs.esmbot.net/custom-commands/

There is a minor typo in the docs' custom command page, "Commnand Structure" instead of "Command Structure"

### Steps to reproduce

1. Go to https://docs.esmbot.net/custom-commands/
2. Scroll a little

### Screenshots

![image](https://user-images.githubusercontent.com/71863699/211175296-dbdb3fd5-4527-42ed-a599-0720e2df8b99.png)

### Self-hosted instance?

No

**Comment by TheEssem** [comment]
Thanks for the catch! Fixed with 21e0914.
