### ISSUE TITLE
Artifacting on small images

### ISSUE THREAD

**Issue by DUCKONAROLL** [esmBot/esmBot#349]
### Describe the bug

Like it says in the title. Using commands such as caption and snapchat leave artifacts on small images.

### Steps to reproduce

1. Get a small image
2. Use a command that adds something without changing the size like caption 
3. See weird artifacting on the result

### Expected behavior

No artifacts & white text

### Screenshots

![19F50712-E098-4947-A07D-8B11179CB610](https://user-images.githubusercontent.com/71863699/211446406-eb5f09e4-d038-4187-8c5b-248cd36e5b32.jpeg)

### Self-hosted instance?

Yes

### Additional context

Self hosted instance but I am pretty sure that isn’t the cause, because I haven’t messed with the image commands.

**Comment by ioletsgo** [comment]
Unless you would want esmbot to upscale the image, it will stay in the same resolution as the source image. The artifacting comes from that.

**Comment by TheEssem** [comment]
If the original image is in JPEG format, then the output will be JPEG as well. Since the JPEG format itself is lossy, more artifacts will be introduced on each encode. Not much can be done about this.

**Comment by DUCKONAROLL** [comment]
ah, I see. Is there a command to convert it to PNG or do I have to do that on my end?
