### ISSUE TITLE
Cannot play soundboard audio after audio has been played

### ISSUE THREAD

**Issue by LawsOfScience** [esmBot/esmBot#351]
### Describe the bug

After you play any type of audio (using either `/music` or `/soundboard`), you cannot play any `/soundboard` sounds again until the bot disconnects.

### Steps to reproduce

1. Make sure esmBot is not already in the VC.
2. Use `/music` or `/soundboard` to play an audio.
3. The bot should join and play what you request.
4. Either skip the audio or wait for it to finish.
5. Try to use a `/soundboard` command again.
6. The bot will state "I can't play a sound effect while other audio is playing!"

### Expected behavior

The bot should play the sound after the audio finishes/is skipped.

### Self-hosted instance?

Yes

### Additional context

Reproducible with both slash commands and message commands.
Additional music (using `/music play`) *will* play after music/soundboard sound has been played.
Bot is configured to *not* leave voice channel after audio finishes playing.
Running bot in Docker container.

Music and soundboard commands cause an "Unknown return type" console warning.
<img width="941" alt="image" src="https://user-images.githubusercontent.com/24637919/212496791-d08ffa38-25a9-4fe6-8925-4cf55771a857.png">
Commands ran to produce above image output:
1. `/soundboard oof` (successfully played)
2. `/music play <query>` (successfully played)
3. `/music skip` (successfully skipped)
4. `/soundboard bruh` (did not play)
5. `/music stop` (bot disconnected)

**Comment by TheEssem** [comment]
I can't seem to reproduce this issue on the main bot, latest commit, or lavalink-v4 branch; is it still happening for you?

**Comment by supern64** [comment]
It's still happening for me... does it have anything to do with me using the Docker image?

**Comment by TheEssem** [comment]
As of 60b0d8e79272acbeab0ff9b96998e0a0e257676a, soundboard commands have been removed, meaning that this issue is no longer possible.
