### ISSUE TITLE
high cpu usage after doing &caption on a huge gif

### ISSUE THREAD

**Issue by mr-nv** [esmBot/esmBot#354]
### Describe the bug

this happens only with gifs that are 8mb or more in size, pic below is cpu usage when the bot finished processing the gif and already sent it

### Steps to reproduce

1. send a huge gif (8 or more megabytes in size) 
2. do &caption, but other image processing commands should work too
3. wait until the bot processes it
4. check the cpu usage

### Screenshots

![image](https://user-images.githubusercontent.com/31269663/216824650-ebd6af55-267d-4c33-ba07-891836cc324f.png)
![image](https://user-images.githubusercontent.com/31269663/216824865-1e36322a-31a4-4e8f-90d0-582eb9c4e55c.png)

### Self-hosted instance?

Yes

**Comment by TheEssem** [comment]
#325 could be a potential cause of this?

**Comment by bjcscat** [comment]
Without knowing the hardware in use by @mr-nv I will hazard a guess that this could be related to #374

**Comment by TheEssem** [comment]
Closing as fixed until OP says otherwise.

**Comment by mr-nv** [comment]
just updated my instance and it seems to work fine now, thanks
@bjcscat 
![image](https://github.com/esmBot/esmBot/assets/31269663/e95b855f-c94f-49d4-801c-18c192952582)
