### ISSUE TITLE
Spotify "This is" template

### ISSUE THREAD

**Issue by aubymori** [esmBot/esmBot#359]
### Describe the request

Many memes feature the spotify "This is" image edited to have different text and a different image. It's a very simple template, and I would love to see it implemented in esmBot.
Template:
![Spotify "This is" template](https://user-images.githubusercontent.com/44238627/224148455-47467500-f8ab-4271-9d71-b241c28b914a.png)

**Comment by aubymori** [comment]
The font seems to be the internal font, which is referred to in the website's CSS as "CircularSp". Not sure if that's the real name or if it even has one.

**Comment by aubymori** [comment]
Found the font file. It's called "Circular Spotify". The variant used here is Circular Spotify Title Bold.
https://encore.scdn.co/fonts/CircularSpTitle-Bold-2fbf72b606d7f0b0f771ea4956a8b4d6.woff2

**Comment by bjcscat** [comment]
seems like a good command

**Comment by bjcscat** [comment]
added in #386

**Comment by TheEssem** [comment]
#386 has been merged, closing.
