### ISSUE TITLE
Problem on the &

### ISSUE THREAD

**Issue by noubanim** [esmBot/esmBot#36]
This is the second issue and idk if this is an issue every server I use the &caption or &motiv and it won’t allowed me get the gif or photo I want can I wait until the time is right for me?
![2DEDA2FD-A367-4E18-B45E-B9D2EA251568](https://user-images.githubusercontent.com/76239677/103326862-e153c980-4a17-11eb-84c4-b9ea776671b6.jpeg)

**Comment by wiisp** [comment]
Is this right now? At this very moment the main esmBot instance is down for maintenance, so it won't respond to anything until it's back up.

**Comment by noubanim** [comment]
Well this happens earlier like 3-4 hours ago. So the maintenance is the problem?

**Comment by wiisp** [comment]
The maintenance started around 4-5 hours ago, so yes.

**Comment by noubanim** [comment]
Damn when it’s going to ended 


Sent from Yahoo Mail for iPhone


On Tuesday, December 29, 2020, 9:02 PM, wiisp <notifications@github.com> wrote:




The maintenance started around 4-5 hours ago, so yes.

**Comment by wiisp** [comment]
The exact time is unknown, during the maintenance we had an issue with the bot database (the database stores things like server prefixes, tags, and disabled channels) and it is being worked on. Because of this maintenance is taking longer than expected and we apologize for any inconveniences it may have caused.

**Comment by noubanim** [comment]
Nah bro it’s okay take your time on maintenance I will wait for my meme ideas later


Sent from Yahoo Mail for iPhone


On Tuesday, December 29, 2020, 9:07 PM, wiisp <notifications@github.com> wrote:




The exact time is unknown, during the maintenance we had an issue with the bot database (the database stores things like server prefixes, tags, and disabled channels) and it is being worked on. Because of this maintenance is taking longer than expected and we apologize for any inconveniences it may have caused.
