### ISSUE TITLE
Twemoji does not work on Raspberry Pi

### ISSUE THREAD

**Issue by dominic-03** [esmBot/esmBot#360]
### Describe the bug

Upon captioning a GIF with an emoji the following result is output from an esmBot instance hosted on a Raspberry Pi:

<img width="307" alt="Screenshot 2023-03-11 at 09 45 17" src="https://user-images.githubusercontent.com/47524785/224490983-62fd32b8-29a4-423a-9636-27dd072f5e67.png">

The GIF is captioned with the Google Noto emoji font, when it should be using Twemoji.

### Steps to reproduce

1. set up bot
2. caption gif
3. sad

### Expected behavior

<img width="297" alt="Screenshot 2023-03-11 at 09 48 09" src="https://user-images.githubusercontent.com/47524785/224491125-7b0d5e2c-824f-44df-873f-023b13b10992.png">

Official instances of esmBot use the Twemoji font.

### Screenshots

they're up there

### Self-hosted instance?

Yes

**Comment by dominic-03** [comment]
still does not work on 1.10.2

**Comment by TheEssem** [comment]
Managed to reproduce in a Docker container, I just modified the existing Dockerfile to install Noto Emoji through apk. I wonder if the fontconfig is messed up or something?

**Comment by dominic-03** [comment]
uninstalled noto emoji font and it works now, weird that it doesn't use twemoji by default tho

**Comment by jcupitt** [comment]
Hey @TheEssem. Yes, some kind of fontconfig thing I guess. I suppose some brave person would need to read the docs and see how to override a global font.

**Comment by TheEssem** [comment]
Fixed with 6e29cdc. I would prefer that libvips handles font loading slightly better, but this should do for now.
