### ISSUE TITLE
Caption Error

### ISSUE THREAD

**Issue by BravoAlpha101st** [esmBot/esmBot#361]
### Command that caused the error

/caption

### Image that caused the error

https://tenor.com/view/trollfacelmaaaao-gif-23938565

### Steps to reproduce

1. Type /caption
2. In the caption text, insert the entire 'You've been trolled' copypasta
3. Add Troll link for the GIF
4. Profit

### Self-hosted instance?

No

### Error file

Message: Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}

Stack Trace: Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)

**Comment by TheEssem** [comment]
Temporary network issue on the main instance
