### ISSUE TITLE
esmBot error

### ISSUE THREAD

**Issue by hwagstaff** [esmBot/esmBot#369]
### Command that caused the error

/ancient

### Steps to reproduce

1. use /ancient command

(It seems to happen pretty regularly but not every time)

### Self-hosted instance?

Yes

### Error file

```

```
[error.txt](https://github.com/esmBot/esmBot/files/11154428/error.txt)

**Comment by TheEssem** [comment]
Is this still happening by chance?

**Comment by hwagstaff** [comment]
It seems fine now it was just happening for a day or two, so all good I guess.
