### ISSUE TITLE
[API] EMFILE: Too many open files

### ISSUE THREAD

**Issue by GmanChewing-HLAModder** [esmBot/esmBot#37]
Message: Error: EMFILE: too many open files, open '/home/esmBot/esmBot/api/index.js'

Stack Trace: undefined

**Comment by Thebombuknow** [comment]
same issue here
bot told me to post this:
Message: Error: EMFILE: too many open files, open '/home/esmBot/esmBot/api/index.js'

Stack Trace: undefined
I'm guessing this is a server-wide issue

**Comment by TheEssem** [comment]
> same issue here
> bot told me to post this:
> Message: Error: EMFILE: too many open files, open '/home/esmBot/esmBot/api/index.js'
> 
> Stack Trace: undefined
> I'm guessing this is a server-wide issue

yeah it's server-wide, I lowered the amount of max image workers slightly just now so that should fix it

still keeping this issue open however in case it continues to happen

**Comment by TheEssem** [comment]
Seems to be fixed for the most part, closing.
