### ISSUE TITLE
Type Error img.image is not a function

### ISSUE THREAD

**Issue by PortalRex** [esmBot/esmBot#371]
### Command that caused the error

/caption anytext

### Image that caused the error

Any images

### Steps to reproduce

1. Do /caption with whatever text and select whatever image
2. Bot errors

### Self-hosted instance?

Yes

### Error file

```
Message: TypeError [Error]: img.image is not a function
    at file:///mnt/c/Users/bot/esmbot/utils/image-runner.js:50:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Stack Trace: TypeError: img.image is not a function
    at file:///mnt/c/Users/bot/esmbot/utils/image-runner.js:50:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by TheEssem** [comment]
Did you make sure to build the natives with `pnpm run build` first?

**Comment by PortalRex** [comment]
Nope, I didn't.... Solved.
