### ISSUE TITLE
Update the 8mb limit to the new 25mb limit

### ISSUE THREAD

**Issue by TheMemeSniper** [esmBot/esmBot#372]
Discord has recently bumped up the old 8mb file upload limit for non-nitro subscribers to 25mb, and the bot's limit should be updated accordingly.

**Comment by TheMemeSniper** [comment]
oh ok

**Comment by AshKmo** [comment]
Limit has been changed to 25mb now for bots. Have tested locally.

**Comment by TheEssem** [comment]
Fixed with 0c867cb
