### ISSUE TITLE
Caption results in no text

### ISSUE THREAD

**Issue by PortalRex** [esmBot/esmBot#373]
### Describe the bug

Using the caption commands spits out an image without any text. I am using wsl2 and have linked the font folders. Unsure why this is happening have tried a fresh install.

### Steps to reproduce

1. Do /caption (input text)
2. Bot gives image missing input text

### Expected behavior

Bot should add input text

### Self-hosted instance?

Yes

**Comment by TheEssem** [comment]
Maybe give 6e29cdc a shot?

**Comment by PortalRex** [comment]
Very late update, apologies, Any attempt of using a text caption command now results in the the following error.

`Fontconfig error: "esmBot/assets/fonts/fontconfig.xml", line 6: invalid attribute 'salt'
Fontconfig error: Cannot load config file from esmBot/assets/fonts/fontconfig.xml`

I am at a total loss here.

**Comment by TheEssem** [comment]
Interesting; what distro and version of fontconfig are you using? The "salt" attribute that it mentions was added in version 2.13.94. (You should be able to check the fontconfig version by running `fc-list --version`.)

**Comment by PortalRex** [comment]
Distro was extremely out of date, 20.04.06 before updating and 22.04.3 after. Problem was fixed after an update. Thank you for the help.
