### ISSUE TITLE
Respect spoilered images

### ISSUE THREAD

**Issue by faejr** [esmBot/esmBot#387]
### Describe the request

When processing a spoilered image using any of the image commands the image that is returned is not spoilered even if the source image is. 

### Is your feature request related to a problem? Please describe.

This can be an issue if it's spoilered due to a CW or other server rules apply to the image.

**Comment by TheEssem** [comment]
One edge case I could think of where this might not work would be the large/external image embeds, since Discord doesn't allow spoilers on those IIRC. Other than that, I do agree that this could be beneficial.

**Comment by faejr** [comment]
Yeah that's an annoying edge case. I know that if you spoiler the link in discord the resulting image also gets spoilered, I wonder if that can somehow work for the large/external image embeds? I'm unsure since you put those in an embed. 🤔

**Comment by TheEssem** [comment]
Finally got around to implementing this, did a test and it appears that putting a link to an image from an external source behind spoiler text doesn't embed the image at all:
![image](https://github.com/esmBot/esmBot/assets/21112968/40d79cde-976c-4385-9060-7048424953e8)
This seems like a big issue; I thought about attempting something on the web server's side to detect requests from Discord and serve a dedicated spoiler image saying to access the site directly, but that could also prove to be more of a hassle for people self-hosting the bot.
