### ISSUE TITLE
qrcreate command doesn't have an option to input text

### ISSUE THREAD

**Issue by SilvanosNelli** [esmBot/esmBot#390]
### Describe the bug

Using the /qrcreate slash command doesn't give the user an option to input text which results in the bot asking for one. Writing the text manually doesn't work either.

### Steps to reproduce

1. Type in the slash command `/qrcreate` in the chat
2. Discord usually shows the user options to fill in, but in this case none is showed. 

### Expected behavior

The slash command is supposed to show the user an option to enter text.

### Screenshots

![image](https://github.com/esmBot/esmBot/assets/39396556/52ff609c-f5d1-4b75-b35f-56d87fc8aef3)
![image](https://github.com/esmBot/esmBot/assets/39396556/686fc5c1-996b-4412-9edc-52fa81507b1d)

### Self-hosted instance?

No

**Comment by TheEssem** [comment]
Should be fixed with c4e40d4, actually quite surprised that I missed this tbh
