### ISSUE TITLE
/speechbubble command error

### ISSUE THREAD

**Issue by fowlis** [esmBot/esmBot#403]
### Command that caused the error

/speechbubble

### Image that caused the error

n/a

### Steps to reproduce

1. Use `/speechbubble` command
2. Result

### Self-hosted instance?

No

### Error file

```
Message: Error: A boolean was expected
    at file:///home/ubuntu/esmBot/utils/image-runner.js:50:39
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Stack Trace: Error: A boolean was expected
    at file:///home/ubuntu/esmBot/utils/image-runner.js:50:39
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by TheEssem** [comment]
Judging by the error given, it looks like this error is from a self-hosted instance. Check if the natives were built properly.
