### ISSUE TITLE
esmBot fails to connect to lavalink/lavaplayer

### ISSUE THREAD

**Issue by mr-nv** [esmBot/esmBot#406]
### Command that caused the error

bot startup and &soundreload

### Self-hosted instance?

Yes

### Error file

```
lavalink          | 2023-08-02T06:50:20.891Z  WARN 1 --- [  XNIO-1 task-2] o.s.web.servlet.PageNotFound             : No mapping for GET /
esmbot-bot-1      | [2023-08-02 06:50:20]: [ERROR] - An error occurred on Lavalink node localhost: Error: Unexpected server response: 404
lavalink          | 2023-08-02T06:50:21.465Z  WARN 1 --- [  XNIO-1 task-2] o.s.web.servlet.PageNotFound             : No mapping for GET /
esmbot-bot-1      | [2023-08-02 06:50:21]: [ERROR] - An error occurred on Lavalink node localhost: Error: Unexpected server response: 404
```

### Additional context

tried to run a esmbot instance on a new vps and ran into this issue
my guess is that esmbot isnt updated to the new lavaplayer versions, because it works fine on 1.3.99.2
![image](https://github.com/esmBot/esmBot/assets/31269663/ffe3629d-e75d-4957-b2aa-97033d2440c8)
and fails to connect on 1.4.2
![image](https://github.com/esmBot/esmBot/assets/31269663/7537fb60-b688-43f7-92df-39c894c3a550)

**Comment by mr-nv** [comment]
lavaplayer isnt the issue, lavalink is
ive manually downloaded the latest version of lavalink (3.7.7), replaced the jar and it started working again

**Comment by lenicyl** [comment]
> lavaplayer isnt the issue, lavalink is ive manually downloaded the latest version of lavalink (https://github.com/lavalink-devs/Lavalink/releases/tag/3.7.7), replaced the jar and it started working again

Thank you this worked !
If you're using docker, for lavalink use the tag `fredboat/lavalink:439f122` (v3.7.8) instead of dev

**Comment by TheEssem** [comment]
esmBot doesn't currently support Lavalink v4 in the main branch; however, there is a WIP port in the `lavalink-v4` branch. 15de37b should force the bot to use v3 with Docker for now.
