### ISSUE TITLE
Bot tries to caption imgur.com mp4 files, then fails

### ISSUE THREAD

**Issue by steveruu** [esmBot/esmBot#408]
### Command that caused the error

caption

### Image that caused the error

https://imgur.com/0OAhgUe

### Steps to reproduce

1. upload/select an imgur.com video file 
2. copy video URL and paste it into Discord
3. &caption the video
4. see error

### Self-hosted instance?

Yes

### Error file

```
Message: Error: VipsForeignLoad: buffer is not in a known format

    at file:///home/ubuntu/esmBot/utils/image-runner.js:70:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Stack Trace: Error: VipsForeignLoad: buffer is not in a known format

    at file:///home/ubuntu/esmBot/utils/image-runner.js:70:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

### Additional context

when you try any other command, it posts an 0 byte empty GIF file without posting any errors

**Comment by chromiik** [comment]
yeah, came across that too

**Comment by bjcscat** [comment]
The bot can't perform operations on .mp4s

**Comment by steveruu** [comment]
yeah Captain Obvious, so make it that it says it's an .mp4 file and not let it send an empty .mp4 file lol

**Comment by TheEssem** [comment]
Is ImageMagick installed on the server? Imgur links are especially difficult to handle since they don't properly store GIF files (or any animated image format) and instead return JPEG or MP4 files.

**Comment by TheEssem** [comment]
Imgur-specific link handling was removed in 5eb0b1414ee9648b8472618f1b5b258ff0331f60. Closing.
