### ISSUE TITLE
Music play: completely unexpected error

### ISSUE THREAD

**Issue by Mimumi372** [esmBot/esmBot#416]
### Command that caused the error

/music play https://www.youtube.com/watch?v=1HLOBG_40gw

### Steps to reproduce

1. Go into a voice channel
2. Use the command
3. See error

### Self-hosted instance?

No

### Error file

```
[error.txt](https://github.com/esmBot/esmBot/files/13260497/error.txt)
```

### Additional context

The command seemed to work just fine yesterday and now it does not. Whatever link I paste it gives out the same error.

**Comment by TheEssem** [comment]
There's a patch included in 60b0d8e.
