### ISSUE TITLE
[docs] nodesource script is being deprecated

### ISSUE THREAD

**Issue by TheMemeSniper** [esmBot/esmBot#420]
### Describe the bug

when running the installer script for nodejs on ubuntu/debian in step 3, the following text appears in the terminal:

```

                           SCRIPT DEPRECATION WARNING                    

  
  This script, located at https://deb.nodesource.com/setup_X, used to
  install Node.js is deprecated now and will eventually be made inactive.

  Please visit the NodeSource distributions Github and follow the
  instructions to migrate your repo.
  https://github.com/nodesource/distributions

  The NodeSource Node.js Linux distributions GitHub repository contains
  information about which versions of Node.js and which Linux distributions
  are supported and how to install it.
  https://github.com/nodesource/distributions
```

there is then a 60 second wait before the script continues

### Steps to reproduce

1. run `curl -fsSL https://deb.nodesource.com/setup_18.x | sudo bash -` in the terminal as described in step 3 of the setup docs
2. see message

### Expected behavior

the script used for setting up nodejs not being deprecated

### Self-hosted instance?

Yes

**Comment by TheEssem** [comment]
The new steps seem a bit more complex, we might need to replace the Nodesource repo steps with another method. Maybe something like nvm, n, or fnm?

**Comment by TheMemeSniper** [comment]
nvm is one of the most user friendly nodejs runtime managers i've tried but i haven't tried the other ones

**Comment by TheEssem** [comment]
nvm might be a good pick here, yeah. Main downside I can think of is that there's no Windows support, but since the bot currently doesn't support Windows (and the guide only has steps for Linux systems anyways) that shouldn't be too much of an issue.
