### ISSUE TITLE
esmbot wont run with pnpm start

### ISSUE THREAD

**Issue by oakguy123** [esmBot/esmBot#422]
### Describe the bug

when following the setup for setting up esmbot i get an error no idea how to fix
```
ubuntu@oak-town:~/esmBot$ pnpm start

> esmbot@1.10.3 start /home/ubuntu/esmBot
> node app.js

file:///home/ubuntu/esmBot/app.js:41
import commandConfig from "./config/commands.json" with { type: "json" };
                                                   ^^^^

SyntaxError: Unexpected token 'with'
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:152:18)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:298:14)
    at async link (node:internal/modules/esm/module_job:67:21)

Node.js v18.19.0
 ELIFECYCLE  Command failed with exit code 1.
ubuntu@oak-town:~/esmBot$
```

### Steps to reproduce

1. follow the steps for seting up esmbot
2. run pnpm start
3. See error ```
ubuntu@oak-town:~/esmBot$ pnpm start

> esmbot@1.10.3 start /home/ubuntu/esmBot
> node app.js

file:///home/ubuntu/esmBot/app.js:41
import commandConfig from "./config/commands.json" with { type: "json" };
                                                   ^^^^

SyntaxError: Unexpected token 'with'
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:152:18)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:298:14)
    at async link (node:internal/modules/esm/module_job:67:21)

Node.js v18.19.0
 ELIFECYCLE  Command failed with exit code 1.
ubuntu@oak-town:~/esmBot$ 
```

### Expected behavior

bot should of started up as normal

### Screenshots

![image](https://github.com/esmBot/esmBot/assets/153047209/f36ea51a-5ef4-4b12-8421-8cdec5c11caf)


### Self-hosted instance?

Yes

### Additional context

_No response_

**Comment by TheEssem** [comment]
Ah, that's caused by an oversight in a recent commit. Pushing a fix.
