### ISSUE TITLE
platform not supported even tho the bot was runing fine before i reinstalled it

### ISSUE THREAD

**Issue by dotheboogey678** [esmBot/esmBot#432]
### Describe the bug

no idea if this is a bug but on arm64 bot wont run before i reinstalled it the bot ran just fine

### Steps to reproduce

1. follow the hosting step
2. run rm -r node_modules and npm install
3. See error

### Expected behavior

bot should run just fine on arm64

### Screenshots

![image](https://github.com/esmBot/esmBot/assets/67087158/734476ff-b5d0-47f3-813a-06e9a9fa0e6e)

### Self-hosted instance?

Yes

**Comment by TheEssem** [comment]
Seems like the linter CLI really doesn't like being installed on other architectures (go figure), will remove it from the dev dependencies.
