### ISSUE TITLE
/bird is offline

### ISSUE THREAD

**Issue by MeesVanHaeren** [esmBot/esmBot#449]
### Describe the bug

shibe.online, the place where the bot gets it's birds from seems to be a lost domain. Because of this the bird comment just times out, and doesnt show a bird

### Steps to reproduce

1. type "/bird" or "/birb"
2. wait for a minute

### Expected behavior

A bird picture is shown

### Screenshots

![image](https://github.com/esmBot/esmBot/assets/117640650/3dd52f22-4c4e-4b74-8676-b7bd1a7009c0)
![image](https://github.com/esmBot/esmBot/assets/117640650/6e2aa0a1-07ec-47c9-9dc8-ae67798b03ec)
![image](https://github.com/esmBot/esmBot/assets/117640650/9f9e3db2-93d3-4b02-b9ca-9581ae788da1)

### Self-hosted instance?

No

**Comment by TheEssem** [comment]
After a quick look at the Wayback Machine, it appears that shibe.online used a variant of this dataset: https://www.vision.caltech.edu/datasets/cub_200_2011/

I could probably host them on [files.projectlounge.pw](https://files.projectlounge.pw) like with ancient/cat.
