### ISSUE TITLE
Use `/attachments/refresh-urls` for attachment URLs without expiry parameters

### ISSUE THREAD

**Issue by Cynosphere** [esmBot/esmBot#461]
### Describe the request

Use `/attachments/refresh-urls` for attachment URLs without expiry parameters

### Is your feature request related to a problem? Please describe.

Attachment URLs without expiry parameters fail the command when using slash commands

### Additional context

```
POST /attachments/refresh-urls
{"attachment_urls": ["url1", ...]}
```

**Comment by IoIxD** [comment]
Isn't using undocumented endpoints like this a super TOS violation? like there's stuff discord would ignore and then there's this?

**Comment by IoIxD** [comment]
> No? If they didn't want bots using it they would've made bots unable to use it.

Fair enough, this just does not seem like something that Discord wants bot devs to use, especically if this can be used on older URLs.
Maybe make a PR to the api docs and see if they accept it to confirm if its allowed/intentionally exposed to bots?

**Comment by IoIxD** [comment]
I'm not speaking on Essem's behalf, his opinion very likely differs from mine, I'm just expressing disbelief that this is something Discord intentionally left open.

Feel free to reopen this, Essem might do it.

**Comment by adryd325** [comment]
From what I understand the attachment expiry was to stop people from using Discord's CDN as personal file hosting. I see no reason why they'd have problems with bots using it to refresh attachments from within Discord.

**Comment by TheEssem** [comment]
Looking at [the original announcement for the change](https://discord.com/channels/613425648685547541/697138785317814292/1157372186160537750) (you'll need to be in the Discord Developers guild to view), it looks like it's intended for bots to be able to refresh attachments:
> To access the attachment CDN link after the link expires, your app will need to fetch a new CDN URL. The API will automatically return valid, non-expired URLs when you access resources that contain an attachment CDN URL, like when retrieving a message.

With this in mind, I don't see much of an issue with implementing this.

**Comment by IoIxD** [comment]
Okay so they just did something that inconviences everyone and then introduced an api endpoint, intended for bots, that completely defeats the point of them doing it.

Good to see this but also wow Discord is mighty stupid sometimes, and you can't blame me for being skeptical at first.
