### ISSUE TITLE
Incorrect Node Version (v18.13.0)

### ISSUE THREAD

**Issue by plathan** [esmBot/esmBot#463]
### Describe the bug

Updated esmBot to latest version as of 7/14/2024 using usual method outlined in documentation (https://docs.esmbot.net/setup/), including downloading and setting Node.js version to v20.15.1. During install and build steps the following warning is generated:  
` WARN  Unsupported engine: wanted: {"node":">=20.12.0"} (current: {"node":"v18.13.0","pnpm":"7.9.3"})`
During run step the same warning is repeated, followed by a recurrence of the issue described here: https://github.com/esmBot/esmBot/issues/422
```
dwinkus@Philippe2:~/esmBot$ sudo pnpm start
 WARN  Unsupported engine: wanted: {"node":">=20.12.0"} (current: {"node":"v18.13.0","pnpm":"7.9.3"})

> esmbot@2024.7.0 start /home/dwinkus/esmBot
> node app.js

file:///home/dwinkus/esmBot/app.js:54
import commandConfig from "./config/commands.json" with { type: "json" };
                                                   ^^^^

SyntaxError: Unexpected token 'with'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
    at async link (node:internal/modules/esm/module_job:68:21)

Node.js v18.13.0
 ELIFECYCLE  Command failed with exit code 1.
```

### Self-hosted instance?

Yes

**Comment by TheEssem** [comment]
This is most likely an issue with your environment rather than esmBot. I'd suggest checking to make sure the Node version being used is actually the version you installed (e.g. using `which node` and `node -v`) and making sure the nvm binaries are in your PATH.
