### ISSUE TITLE
Command /command nonexistent

### ISSUE THREAD

**Issue by iiDk-the-actual** [esmBot/esmBot#466]
### Describe the bug

Might be a me issue, but for some reason the command /command, usually used to disable or enable commands, just doesn't exist anymore. From the command list on https://esmbot.net/help.html#general, there is a command named command. It disables and enables commands. It's not working, nor is it registered at all.

### Steps to reproduce

1. Go to a channel
2. Type /command
3. Watch in amazement as nothing appears

### Expected behavior

![image](https://github.com/user-attachments/assets/1761ca48-f3ce-4220-b6a6-05c7da8d299e)
It's supposed to just be here

### Self-hosted instance?

No

**Comment by TheEssem** [comment]
The "command" command is meant only for usage with classic commands, which the main instance of esmBot does not support. Discord has its own system for limiting application commands, making a dedicated command for doing so redundant.

To restrict usage of specific commands on your server, head into Server Settings -> Integrations -> esmBot; there's a commands section that allows setting role/channel overrides.
