### ISSUE TITLE
outdated youtube plugin for lavalink

### ISSUE THREAD

**Issue by blushfulcorn** [esmBot/esmBot#473]
### Describe the bug

the current application.yml tells lavalink to load a yt plugin version that's now 2 months old, always resulting in a 403 error

### Steps to reproduce

1. run the bot following the selfhost guide verbatim

### Expected behavior

the video plays in a vc

### Self-hosted instance?

Yes

### Additional context

easy to fix; change line 26 to say 1.7.2

**Comment by TheEssem** [comment]
Fixed with db7ad08
