### ISSUE TITLE
esmBot error file

### ISSUE THREAD

**Issue by xXSilverwolf44Xx** [esmBot/esmBot#5]
Bot told me to post this here:

[error.txt](https://github.com/TheEssem/esmBot/files/4631290/error.txt)

**Comment by TheEssem** [comment]
Looks like the error has to do with the server not having enough resources to run another ImageMagick process, been meaning to look into ways to mitigate this for a while now and this seems like a good time to do so

**Comment by TheEssem** [comment]
Pretty much fixed with 1.4.
