### ISSUE TITLE
Cmmd problems

### ISSUE THREAD

**Issue by Corrupt-Inferno** [esmBot/esmBot#54]
Pretty much all cmmds except &help, &invite, etc. won’t work at all

**Comment by TheEssem** [comment]
What do you mean exactly by it not working? Can you elaborate further?

**Comment by Corrupt-Inferno** [comment]
what else could I mean? they are just straight not working, I'll send the cmmd and they don't pop up, if anything it pops up with the "GitHub help" link thing

**Comment by Corrupt-Inferno** [comment]
and even that by itself is rare
it's also happening on another discord with the bot, for other people and not just me

**Comment by Corrupt-Inferno** [comment]
the discord is the unofficial CSO (classic sonic online) server (a Roblox game community server)

**Comment by TheEssem** [comment]
> what else could I mean? they are just straight not working, I'll send the cmmd and they don't pop up, if anything it pops up with the "GitHub help" link thing

What’s in the text file that the bot sends?

**Comment by TheEssem** [comment]
No response in a month and a half, will reopen once OP responds.
