### ISSUE TITLE
Slow as hell

### ISSUE THREAD

**Issue by lighterlightbulb** [esmBot/esmBot#55]

**Comment by lighterlightbulb** [comment]
Explain to me how a bot taking 1 hour to respond is "invalid"

**Comment by wiisp** [comment]
lets see here, where is your supplied error text file? are you self hosting your own instance? is it a specific error on our public bot instance? if you do not have any of this, you have come to the wrong place and your issue was rightfully closed and marked as invalid.

**Comment by lighterlightbulb** [comment]
Umm uhh uhh umm no text file, no, yes

**Comment by TheEssem** [comment]
> Explain to me how a bot taking 1 hour to respond is "invalid"

While the slowness is indeed a real issue, this issue tracker is mostly intended for issues with the bot software/code itself (as well as some issues with server configuration). The image processing being very slow is due to the "queue" system on the image API being overloaded by the amount of pending jobs, which is (for the most part) a result of the amount of people attempting to generate images at once as well as only having a single server to process these images. A more stable API implementation is currently being tested on the dev bot in the support server, and we are working on moving many image jobs to an external server.

**Comment by lighterlightbulb** [comment]
K fix it

**Comment by lighterlightbulb** [comment]
-rep

**Comment by te-agma-at** [comment]
> > Explain to me how a bot taking 1 hour to respond is "invalid"
> 
> While the slowness is indeed a real issue, this issue tracker is mostly intended for issues with the bot software/code itself (as well as some issues with server configuration). The image processing being very slow is due to the "queue" system on the image API being overloaded by the amount of pending jobs, which is (for the most part) a result of the amount of people attempting to generate images at once as well as only having a single server to process these images. A more stable API implementation is currently being tested on the dev bot in the support server, and we are working on moving many image jobs to an external server.

Wait why isn't this done yet-

**Comment by TheEssem** [comment]
> > > Explain to me how a bot taking 1 hour to respond is "invalid"
> > 
> > While the slowness is indeed a real issue, this issue tracker is mostly intended for issues with the bot software/code itself (as well as some issues with server configuration). The image processing being very slow is due to the "queue" system on the image API being overloaded by the amount of pending jobs, which is (for the most part) a result of the amount of people attempting to generate images at once as well as only having a single server to process these images. A more stable API implementation is currently being tested on the dev bot in the support server, and we are working on moving many image jobs to an external server.
> 
> Wait why isn't this done yet-

It's been done for a bit of time now, however scaling and memory limits are still an issue. More server upgrades might be needed, and it would likely be beneficial to look into a cloud-based solution for running the image jobs (e.g. Kubernetes). Eventually, I'd like to port most of the image functions to another library; however, it could prove to be a major undertaking.
