### ISSUE TITLE
esmBot doesn't execute image/gif manipulation commands (&motivate, &caption...) properly

### ISSUE THREAD

**Issue by linearaccelerator** [esmBot/esmBot#56]
When I type a command (like &motivate), esmBot says that it is processing the image, but doesn't send it at all, and doesn't delete the message

Screenshots: 
![image](https://user-images.githubusercontent.com/64271566/104917397-a4824f00-5993-11eb-9d21-a12211f5d5db.png)
![image](https://user-images.githubusercontent.com/64271566/104917421-ad732080-5993-11eb-89d7-55b7e82b89a7.png)
![image](https://user-images.githubusercontent.com/64271566/104917443-b49a2e80-5993-11eb-9843-ae968831aa8a.png)

note: This issue has been going on for days now

**Comment by linearaccelerator** [comment]
esmBot also doesn't send any error log file(s), as it would on other errors

**Comment by TheEssem** [comment]
read this for more info about what’s going on: https://github.com/esmBot/esmBot/issues/55#issuecomment-761949257

**Comment by lighterlightbulb** [comment]
Basically he's saying that it's slow as hell

**Comment by adroitwhiz** [comment]
why esmbot no work??? pls to halp????

**Comment by lighterlightbulb** [comment]
He need 2 fix it.

**Comment by longdas** [comment]
he pays for the servers for this FREE BOT that have to process all this out of his own pocket. consider donating to the patreon and it will enable him to upgrade the hardware. 

if that isn't an option, you could always host it yourself.

**Comment by lightbulblighter** [comment]
Hi hun!! This issue was made over a month ago

**Comment by linearaccelerator** [comment]
this issue seems to have resolved itself now

**Comment by linearaccelerator** [comment]
nvm it seems to be persisting

**Comment by TheEssem** [comment]
Since the WebSocket reimplementation, the endless processing messages seem to be no more. In addition, the bot now uses multiple servers for image processing, so there should be much more room to handle it. Closing this again for now, however feel free to reopen if these issues start happening again.

**Comment by TheShinyKeldeo** [comment]
It is happening once again, I'm afraid
