### ISSUE TITLE
Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by TravellingTARDIS** [esmBot/esmBot#70]
I'm not sure if this extends to all commands but we've tried a lot of the image commands (mostly caption, magik and speed) and they all seem to be throwing this same error

Message: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

Stack Trace: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at new NodeError (node:internal/errors:329:5)
    at Socket.Writable.write (node:internal/streams/writable:331:11)
    at /home/esmBot/esmBot/utils/image.js:113:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

**Comment by TheEssem** [comment]
This was a result of the image API restarting during an image job. Should (mostly) be a one-time thing.

**Comment by TheEssem** [comment]
Never mind, it wasn't. Reopening.

**Comment by TheEssem** [comment]
Seems to be fixed for sure with the migration to WebSockets on the API. Closing.
