### ISSUE TITLE
Giphy GIFs don't download as an image

### ISSUE THREAD

**Issue by ryno9766** [esmBot/esmBot#72]
I keep on running into an issue where when I try to use &caption with media tenor gifs. Please fix this soon so I can make epic mems.

**Comment by TheEssem** [comment]
What's the error you get when you run it?

**Comment by ryno9766** [comment]
Here, I will attach an image that should explain it. As well as how I got here. I tried it on a gif from Giphy. I didn't mean to say Tenor. Just was mistaken. Tenor gifs work fine with the &caption command.
![image](https://user-images.githubusercontent.com/79945920/109735072-b86ec280-7b87-11eb-937b-97664a443dca.png)

**Comment by TheEssem** [comment]
Ah, Giphy gifs tend to be a moving target because of how they switch between downloading as a webpage and downloading as an image. Been trying to look into this lately.

**Comment by TheEssem** [comment]
Seems to be solved, closing.
