### ISSUE TITLE
Loophole to ping a role

### ISSUE THREAD

**Issue by Yokothecat1** [esmBot/esmBot#73]
I was messing around with the bot and made a loophole to illegally ping a role. (If the bot has admin perms)
By running this command &qrcreate `g` fdsuoh``` test <@&role id>,
(g, fdsuoh and test are obviously placeholders)
i mananged to make a qr code that when read, will ping a role

i know this is very un-professional, but i just wanted to point this out somewhere

**Comment by TheEssem** [comment]
Already fixed with a8db0a1
