### ISSUE TITLE
&retro is not working

### ISSUE THREAD

**Issue by ronaldgamer890** [esmBot/esmBot#82]
[error.txt](https://github.com/esmBot/esmBot/files/6155070/error.txt)
when using this command this error shows up

**Comment by TheEssem** [comment]
I was worried that it would stop working at some point with how long it's been since the API module for it was worked on. The original developer seems to have abandoned the module, so I might have to manage it myself from now on. Gonna look into how I can fix it.

**Comment by LewisTehMinerz** [comment]
From an investigation into this issue I have come to the conclusion that the service used to provide these images has blanket banned IP ranges relating to certain hosting providers. For example, on a Hetzner-provided dedicated server it returns 403 Forbidden whilst on a Contabo VPS it returns the expected 302 Found. The solution would be to rent some cheap server to use as a proxy, although I doubt they'll like that very much and will end up banning it.

I'm not sure if there's a practical fix for this that self-hosters and Essem can do without circumventing bans.

**Comment by TheEssem** [comment]
An alternative implementation that doesn't rely on Photofunia has been introduced, note however that said implementation is vastly different from the old one.
