### ISSUE TITLE
Stop "expiring images" and just upload to imgur

### ISSUE THREAD

**Issue by tymur999** [esmBot/esmBot#85]
Stop making images 'expired'. I'm surprised no one's thought of this, but just store images on imgur. They will never expire. How has no one thought of this yet?

**Comment by tymur999** [comment]
They have their own REST api too. Just saying. You can upload images programmatically

**Comment by TheEssem** [comment]
Imgur's file processing and limits are too restricting. Not only are static images over 5 MB are converted automatically into JPEGs, but images over 1 MB (5 MB for registered accounts) have lossy compression applied which can reduce the quality of the result image. Animated GIF files over 2 MB (!) are also converted to their "gifv" format (essentially just a renamed MP4) which are harder for the bot to process as an image.

Source: https://help.imgur.com/hc/en-us/articles/115000083326-What-files-can-I-upload-What-is-the-size-limit-

**Comment by tymur999** [comment]
What's the use of image quality if the meme is still there?

**Comment by tymur999** [comment]
But that makes sense, so I will close this now.
