### ISSUE TITLE
&caption doesn't work

### ISSUE THREAD

**Issue by zlivx** [esmBot/esmBot#86]
I tried to &caption some of my gifs and it appears to be broken
Here's the error content:
Message: TypeError: Cannot read property 'once' of undefined

Stack Trace: TypeError: Cannot read property 'once' of undefined
    at /home/esmBot/esmBot/utils/image.js:193:20

**Comment by TheEssem** [comment]
Seems like an issue regarding bot startup, it throws that error when there aren't any image processing servers that the bot can access. You should be able to wait a bit and it should work. I should probably add a more proper message for cases like these...
