### ISSUE TITLE
Error when executing &reverse 

### ISSUE THREAD

**Issue by sr3323** [esmBot/esmBot#89]
Message: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

Stack Trace: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at new NodeError (node:internal/errors:329:5)
    at Socket.Writable.write (node:internal/streams/writable:331:11)
    at /home/esmBot/esmBot/utils/image.js:109:21

This happened when i tried to reverse this gif https://tenor.com/view/catan-tableflip-i-quit-you-cheater-angry-gif-4955758

**Comment by TheEssem** [comment]
Seems like something happened with the connection to the image servers, should be fixed now.
