### ISSUE TITLE
Failed to convert image into jpeg.

### ISSUE THREAD

**Issue by owlw** [esmBot/esmBot#91]
```
Message: TypeError: Cannot read property 'once' of undefined

Stack Trace: TypeError: Cannot read property 'once' of undefined
    at /home/esmBot/esmBot/utils/image.js:193:20
```

**Comment by javathunderman** [comment]
Can confirm that I'm getting the same error while trying to do gif manipulation (&speed, &globe, etc.): 
![image](https://user-images.githubusercontent.com/6887325/115294022-0e8ec980-a126-11eb-917e-39d1cf752520.png)

**Comment by TheEssem** [comment]
Seems like a duplicate of #86, the fixes are already in master and should be arriving with the next release.
