### ISSUE TITLE
"get real" check in caption command can be bypassed using unicode characters

### ISSUE THREAD

**Issue by kittrz9** [esmBot/esmBot#93]
In the caption.js file, the check for if the given caption is just the string "get real" can easily be bypassed by using unicode characters like the zero width space.

The current check is `if (newCaption.toLowerCase() === "get real")`. A check that could work is to use a regex to get rid of all non-ASCII characters in the check. The check could probably be replaced with something like `if (newCaption.toLowerCase().replace(/[\u{0080}-\u{FFFF}\u{00}-\u{19}]/gu, "") === "get real")`. 

I don't really like the solution I came up with though since the regex just looks weird (Though that's probably just because I'm just not really used to working with them and javascript) so there's probably a more elegant solution to this or something. I have tested this a bit using node.js and it seems to work, though there is probably more ways to bypass the check.

Sorry if this was like intended or something, I might just be dumb.

**Comment by LewisTehMinerz** [comment]
i mean if you're trying that hard to bypass the check then you deserve to be blessed with a clean 'get real'.

on a serious note, its a very unserious meme. i have a feeling that an extremely complicated check will not be implemented.

**Comment by kittrz9** [comment]
Yeah it makes sense to not really need the check because of how the get real check is for a joke, but idk I thought it would be funny to have an overengineered solution just for the get real joke. Sorry for being dumb
